(function(g){var window=this;var bGa=function(a,b){return g.Tb(a,b)},$5=function(a,b,c){a.C.set(b,c)},a6=function(a){$5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.A()).toString(36));
return a},b6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.ln(a.C,b,c)},cGa=function(a,b){var c=[];
g.dj(b,function(d){try{var e=g.Yn.prototype.B.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Xn(e)&&c.push(d)},a);
return c},dGa=function(a,b){var c=cGa(a,b);
g.Gb(c,function(d){g.Yn.prototype.remove.call(this,d)},a)},eGa=function(a){if(a.Ld){if(a.Ld.locationOverrideToken)return{locationOverrideToken:a.Ld.locationOverrideToken};
if(null!=a.Ld.latitudeE7&&null!=a.Ld.longitudeE7)return{latitudeE7:a.Ld.latitudeE7,longitudeE7:a.Ld.longitudeE7}}return null},fGa=function(a,b){g.nb(a,b)||a.push(b)},c6=function(a){var b=0,c;
for(c in a)b++;return b},gGa=function(a,b){var c=b instanceof g.Fc?b:g.Lc(b,/^data:image\//i.test(b));
a.src=g.Gc(c)},d6=function(){},hGa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},iGa=function(a){if(a.Ye&&"function"==typeof a.Ye)return a.Ye();
if("string"===typeof a)return a.split("");if(g.Ra(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Pb(a)},jGa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ra(a)||"string"===typeof a)g.Gb(a,b,void 0);else{if(a.lg&&"function"==typeof a.lg)var c=a.lg();else if(a.Ye&&"function"==typeof a.Ye)c=void 0;else if(g.Ra(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Qb(a);d=iGa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},kGa=function(a,b,c,d){var e=new g.Zm(null,void 0);
a&&g.$m(e,a);b&&g.an(e,b);c&&g.bn(e,c);d&&(e.B=d);return e},e6=function(a,b){g.Lo[a]=!0;
var c=g.Jo();c&&c.publish.apply(c,arguments);g.Lo[a]=!1},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Wm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",lGa(this,a.capabilities||""),mGa(this,a.experiments||""))},lGa=function(a,b){a.capabilities.clear();
g.Ke(b.split(","),g.Wa(bGa,nGa)).forEach(function(c){a.capabilities.add(c)})},mGa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},oGa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},pGa=function(a){return new g6(a)},qGa=function(a){return Array.isArray(a)?g.Pc(a,pGa):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return Array.isArray(a)?"["+g.Pc(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},rGa=function(a){return g.Pc(a,function(b){return{key:b.id,
name:b.name}})},l6=function(a,b){return g.jb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},m6=function(a,b){return g.jb(a,function(c){return h6(c,b)})},sGa=function(){var a=(0,g.Ps)();
a&&dGa(a,a.u.yi(!0))},n6=function(){var a=g.Ss("yt-remote-connected-devices")||[];
g.Cb(a);return a},tGa=function(a){if(g.ob(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Pc(a,function(d,e){return 0==e?d:d.substring(c.length)})},uGa=function(a){g.Rs("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.Ss("yt-remote-device-id");a||(a=k6(),g.Rs("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.nb(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.nb(a,b);g.Us()&&g.Fb(a,b);a=tGa(a);if(g.ob(a))try{g.xq("remote_sid")}catch(c){}else try{g.vq("remote_sid",a.join(","),-1)}catch(c){}},vGa=function(){return g.Ss("yt-remote-session-browser-channel")},wGa=function(){return g.Ss("yt-remote-local-screens")||[]},xGa=function(){g.Rs("yt-remote-lounge-token-expiration",!0,86400)},yGa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Pc(wGa(),function(d){return d.loungeToken}),c=g.Pc(a,function(d){return d.loungeToken});
g.jh(c,function(d){return!g.nb(b,d)})&&xGa();
g.Rs("yt-remote-local-screens",a,31536E3)},zGa=function(a,b){g.Rs("yt-remote-session-browser-channel",a);
g.Rs("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.nb(c,d)||c.push(d);uGa(c);q6()},r6=function(a){a||(g.Ts("yt-remote-session-screen-id"),g.Ts("yt-remote-session-video-id"));
q6();a=n6();g.rb(a,p6());uGa(a)},AGa=function(){if(!s6){var a=g.io();
a&&(s6=new g.Sn(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},BGa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},CGa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},t6=function(a){a.length?DGa(a.shift(),function(){t6(a)}):u6()},EGa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},DGa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.jd(d,g.ng(a));(document.head||document.documentElement).appendChild(d)},u6=function(){var a=CGa();
a&&a(!1,"No cast extension found")},GGa=function(){if(FGa){var a=2,b=CGa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;DGa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",u6,c)}},HGa=function(){GGa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);t6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},v6=function(a,b,c){g.B.call(this);
this.I=null!=c?(0,g.z)(a,c):a;this.Ke=b;this.F=(0,g.z)(this.DI,this);this.u=!1;this.B=0;this.C=this.Ua=null;this.D=[]},w6=function(a,b,c){g.B.call(this);
this.D=null!=c?a.bind(c):a;this.Ke=b;this.C=null;this.u=!1;this.B=0;this.Ua=null},x6=function(a){a.Ua=g.Um(function(){a.Ua=null;
a.u&&!a.B&&(a.u=!1,x6(a))},a.Ke);
var b=a.C;a.C=null;a.D.apply(null,b)},y6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return hGa(a)},z6=function(){},A6=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},C6=function(a){B6.dispatchEvent(new IGa(B6,a))},IGa=function(a){g.Ll.call(this,"statevent",a)},D6=function(){},JGa=function(){},LGa=function(a){return(a=KGa(a))?new ActiveXObject(a):new XMLHttpRequest},KGa=function(a){if(!a.B&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.B=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.B},E6=function(a,b,c,d){this.u=a;
this.B=b;this.P=c;this.K=d||1;this.F=45E3;this.D=new g.V0(this);this.C=new g.Tm;this.C.setInterval(250)},NGa=function(a,b,c){a.Cn=1;
a.Fj=a6(b.clone());a.Ml=c;a.I=!0;MGa(a,null)},F6=function(a,b,c,d,e){a.Cn=1;
a.Fj=a6(b.clone());a.Ml=null;a.I=c;e&&(a.AF=!1);MGa(a,d)},MGa=function(a,b){a.un=g.A();
G6(a);a.uk=a.Fj.clone();b6(a.uk,"t",a.K);a.rq=0;a.Nd=a.u.Fv(a.u.Yp()?b:null);0<a.rw&&(a.Ht=new w6((0,g.z)(a.AG,a,a.Nd),a.rw));a.D.ra(a.Nd,"readystatechange",a.bQ);var c=a.nl?g.Zb(a.nl):{};a.Ml?(a.pu="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Nd.send(a.uk,a.pu,a.Ml,c)):(a.pu="GET",a.AF&&!g.Ae&&(c.Connection="close"),a.Nd.send(a.uk,a.pu,null,c));a.u.hh(1)},QGa=function(a,b,c){for(var d=!0;!a.Pk&&a.rq<c.length;){var e=OGa(a,c);
if(e==H6){4==b&&(a.Tj=4,C6(15),d=!1);break}else if(e==PGa){a.Tj=4;C6(16);d=!1;break}else I6(a,e)}4==b&&0==c.length&&(a.Tj=1,C6(17),d=!1);a.ph=a.ph&&d;d||(J6(a),K6(a))},OGa=function(a,b){var c=a.rq,d=b.indexOf("\n",c);
if(-1==d)return H6;c=Number(b.substring(c,d));if(isNaN(c))return PGa;d+=1;if(d+c>b.length)return H6;var e=b.substr(d,c);a.rq=d+c;return e},TGa=function(a,b){a.un=g.A();
G6(a);var c=b?window.location.hostname:"";a.uk=a.Fj.clone();$5(a.uk,"DOMAIN",c);$5(a.uk,"t",a.K);try{a.wh=new ActiveXObject("htmlfile")}catch(n){J6(a);a.Tj=7;C6(22);K6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)h=e+"\\x3c";else if(">"==h)h=e+"\\x3e";else{if(h in L6)h=L6[h];else if(h in SGa)h=L6[h]=SGa[h];else{var l=h.charCodeAt(0);if(31<l&&127>l)var m=h;else{if(256>l){if(m="\\x",16>l||256<l)m+="0"}else m="\\u",4096>l&&(m+="0");m+=l.toString(16).toUpperCase()}h=
L6[h]=m}h=e+h}e=h}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.gd(g.kc("b/12014412"),d+"</body></html>");a.wh.open();a.wh.write(g.cd(c));a.wh.close();a.wh.parentWindow.m=(0,g.z)(a.pP,a);a.wh.parentWindow.d=(0,g.z)(a.zE,a,!0);a.wh.parentWindow.rpcClose=(0,g.z)(a.zE,a,!1);c=a.wh.createElement("DIV");a.wh.parentWindow.document.body.appendChild(c);d=g.Kc(a.uk.toString());d=g.nd(g.Gc(d));d=g.gd(g.kc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.hd(c,d);a.u.hh(1)},G6=function(a){a.bz=g.A()+a.F;
UGa(a,a.F)},UGa=function(a,b){if(null!=a.In)throw Error("WatchDog timer not null");
a.In=A6((0,g.z)(a.BP,a),b)},M6=function(a){a.In&&(g.v.clearTimeout(a.In),a.In=null)},K6=function(a){a.u.GB()||a.Pk||a.u.Sr(a)},J6=function(a){M6(a);
g.eg(a.Ht);a.Ht=null;a.C.stop();g.Yza(a.D);if(a.Nd){var b=a.Nd;a.Nd=null;b.abort();b.dispose()}a.wh&&(a.wh=null)},I6=function(a,b){try{a.u.rE(a,b),a.u.hh(4)}catch(c){}},WGa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;VGa(a,b,function(h){h?c(!0):g.v.setTimeout(function(){WGa(a,b,c,d,f)},f)})}},VGa=function(a,b,c){var d=new Image;
d.onload=function(){try{N6(d),c(!0)}catch(e){}};
d.onerror=function(){try{N6(d),c(!1)}catch(e){}};
d.onabort=function(){try{N6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{N6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
gGa(d,a)},N6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},O6=function(a){g.im.call(this);
this.headers=new g.Wm;this.ba=a||null;this.B=!1;this.Y=this.u=null;this.oa=this.N="";this.I=0;this.D="";this.F=this.ha=this.P=this.fa=!1;this.K=0;this.V=null;this.ya="";this.X=this.da=!1},XGa=function(a){return g.ye&&g.$d(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},YGa=function(a){return"content-type"==a.toLowerCase()},$Ga=function(a,b){a.B=!1;
a.u&&(a.F=!0,a.u.abort(),a.F=!1);a.D=b;a.I=5;ZGa(a);P6(a)},ZGa=function(a){a.fa||(a.fa=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},bHa=function(a){if(a.B&&"undefined"!=typeof g.$0)if(a.Y[1]&&4==Q6(a)&&2==a.getStatus())R6(a,"Local request error detected and ignored");
else if(a.P&&4==Q6(a))g.Um(a.nE,0,a);else if(a.dispatchEvent("readystatechange"),4==Q6(a)){R6(a,"Request complete");a.B=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.xd(1,String(a.N));if(!f&&g.v.self&&g.v.self.location){var h=g.v.self.location.protocol;f=h.substr(0,h.length-1)}e=!aHa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.I=6;try{var l=2<Q6(a)?a.u.statusText:""}catch(m){l=""}a.D=l+" ["+a.getStatus()+"]";ZGa(a)}}finally{P6(a)}}},P6=function(a,b){if(a.u){cHa(a);
var c=a.u,d=a.Y[0]?g.Oa:null;a.u=null;a.Y=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},cHa=function(a){a.u&&a.X&&(a.u.ontimeout=null);
a.V&&(g.v.clearTimeout(a.V),a.V=null)},Q6=function(a){return a.u?a.u.readyState:0},S6=function(a){try{return a.u?a.u.responseText:""}catch(b){return""}},R6=function(a,b){return b+" ["+a.oa+" "+a.N+" "+a.getStatus()+"]"},dHa=function(a){this.u=a;
this.B=new z6},eHa=function(a){var b=T6(a.u,a.ao,"/mail/images/cleardot.gif");
a6(b);WGa(b.toString(),5E3,(0,g.z)(a.EH,a),3,2E3);a.hh(1)},V6=function(a){var b=a.u.P;
if(null!=b)C6(5),b?(C6(11),U6(a.u,a,!1)):(C6(12),U6(a.u,a,!0));else if(a.If=new E6(a,void 0,void 0,void 0),a.If.nl=a.pw,b=a.u,b=T6(b,b.Yp()?a.Go:null,a.qw),C6(5),!g.ye||g.ae(10))b6(b,"TYPE","xmlhttp"),F6(a.If,b,!1,a.Go,!1);else{b6(b,"TYPE","html");var c=a.If;a=!!a.Go;c.Cn=3;c.Fj=a6(b.clone());TGa(c,a)}},W6=function(a,b,c){this.Ca=1;
this.u=[];this.C=[];this.D=new z6;this.K=a||null;this.P=null!=b?b:null;this.F=c||!1},fHa=function(a,b){this.u=a;
this.map=b;this.context=null},gHa=function(a,b,c,d){g.Ll.call(this,"timingevent",a);
this.size=b;this.Qp=d},hHa=function(a){g.Ll.call(this,"serverreachability",a)},kHa=function(a){iHa(a);
if(3==a.Ca){var b=a.qp++,c=a.wr.clone();$5(c,"SID",a.B);$5(c,"RID",b);$5(c,"TYPE","terminate");X6(a,c);b=new E6(a,a.B,b,void 0);b.Cn=2;b.Fj=a6(c.clone());gGa(new Image,b.Fj.toString());b.un=g.A();G6(b)}jHa(a)},lHa=function(a){a.aI(1,0);
a.wr=T6(a,null,a.ow);Y6(a)},iHa=function(a){a.Ij&&(a.Ij.abort(),a.Ij=null);
a.md&&(a.md.cancel(),a.md=null);a.Ai&&(g.v.clearTimeout(a.Ai),a.Ai=null);Z6(a);a.yf&&(a.yf.cancel(),a.yf=null);a.Mj&&(g.v.clearTimeout(a.Mj),a.Mj=null)},mHa=function(a,b){if(0==a.Ca)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new fHa(a.VL++,b));2!=a.Ca&&3!=a.Ca||Y6(a)},Y6=function(a){a.yf||a.Mj||(a.Mj=A6((0,g.z)(a.yE,a),0),a.Cm=0)},oHa=function(a,b){if(1==a.Ca){if(!b){a.qp=Math.floor(1E5*Math.random());
var c=a.qp++,d=new E6(a,"",c,void 0);d.nl=a.Hm;var e=$6(a),f=a.wr.clone();$5(f,"RID",c);$5(f,"CVER","1");X6(a,f);NGa(d,f,e);a.yf=d;a.Ca=2}}else 3==a.Ca&&(b?nHa(a,b):0==a.u.length||a.yf||nHa(a))},nHa=function(a,b){if(b)if(6<a.Qk){a.u=a.C.concat(a.u);
a.C.length=0;var c=a.qp-1;var d=$6(a)}else c=b.P,d=b.Ml;else c=a.qp++,d=$6(a);var e=a.wr.clone();$5(e,"SID",a.B);$5(e,"RID",c);$5(e,"AID",a.Tm);X6(a,e);c=new E6(a,a.B,c,a.Cm+1);c.nl=a.Hm;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.yf=c;NGa(c,e,d)},X6=function(a,b){if(a.Ge){var c=a.Ge.hB();
c&&g.Jb(c,function(d,e){$5(b,e,d)})}},$6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.Qk&&0<b){var d=a.u[0].u;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={hm:e.hm},f++){e.hm=a.u[f].u;var h=a.u[f].map;e.hm=6>=a.Qk?f:e.hm-d;try{g.Jb(h,function(l){return function(m,n){c.push("req"+l.hm+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.hm+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.u.splice(0,b));
return c.join("&")},pHa=function(a){a.md||a.Ai||(a.I=1,a.Ai=A6((0,g.z)(a.xE,a),0),a.lm=0)},a7=function(a){if(a.md||a.Ai||3<=a.lm)return!1;
a.I++;a.Ai=A6((0,g.z)(a.xE,a),qHa(a,a.lm));a.lm++;return!0},U6=function(a,b,c){a.mu=c;
a.Ph=b.Pi;a.F||lHa(a)},Z6=function(a){null!=a.Vk&&(g.v.clearTimeout(a.Vk),a.Vk=null)},qHa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},b7=function(a,b){if(2==b||9==b){var c=null;
a.Ge&&(c=null);var d=(0,g.z)(a.HQ,a);c||(c=new g.Zm("//www.google.com/images/cleardot.gif"),a6(c));VGa(c.toString(),1E4,d)}else C6(2);rHa(a,b)},rHa=function(a,b){a.Ca=0;
a.Ge&&a.Ge.uA(b);jHa(a);iHa(a)},jHa=function(a){a.Ca=0;
a.Ph=-1;if(a.Ge)if(0==a.C.length&&0==a.u.length)a.Ge.qv();else{g.ub(a.C);var b=g.ub(a.u);a.C.length=0;a.u.length=0;a.Ge.qv(b)}},T6=function(a,b,c){var d=g.gn(c);
if(""!=d.u)b&&g.an(d,b+"."+d.u),g.bn(d,d.D);else{var e=window.location;d=kGa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.vo&&g.Jb(a.vo,function(f,h){$5(d,h,f)});
$5(d,"VER",a.Qk);X6(a,d);return d},sHa=function(){},tHa=function(){this.u=[];
this.B=[]},uHa=function(a,b){this.action=a;
this.params=b||{}},c7=function(a,b){g.B.call(this);
this.u=new g.H(this.iP,0,this);g.C(this,this.u);this.Ke=5E3;this.B=0;if("function"===typeof a)b&&(a=(0,g.z)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.C=a},d7=function(a,b,c,d){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
this.V=a;this.I=b;this.C=new g.Rn;this.B=new c7(this.nQ,this);this.u=null;this.Bd=!1;this.F=null;this.N="";this.P=this.D=0;this.K=[];this.Y=c;this.X=d},vHa=function(a){return{firstTestResults:[""],
secondTestResults:!a.u.mu,sessionId:a.u.B,arrayId:a.u.Tm}},wHa=function(a,b){a.P=b||0;
a.B.stop();e7(a);a.u&&(3==a.u.Ca&&oHa(a.u),kHa(a.u));a.P=0},f7=function(a){return!!a.u&&3==a.u.Ca},e7=function(a){if(a.u){var b=a.X(),c=a.u.Hm||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.u.Hm=c}},xHa=function(a,b){(a.I.loungeIdToken=b)||a.B.stop()},g7=function(a){this.scheme="https";
this.port=this.domain="";this.u="/api/lounge";this.B=!0;a=a||document.location.href;var b=Number(g.xd(4,a))||"";b&&(this.port=":"+b);this.domain=g.yd(a)||"";a=g.Vc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Dc(a,"10.0")&&(this.B=!1))},h7=function(a,b){var c=a.u;
a.B&&(c=a.scheme+"://"+a.domain+a.port+a.u);return g.Ld(c+b,{})},i7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Wa(a.D,d,!0),onError:g.Wa(a.C,e),Df:g.Wa(a.F,e)};c&&(a.Xb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.oq(b,a)},BHa=function(){var a=yHa;
zHa();j7.push(a);AHa(j7)},k7=function(a,b){zHa();
var c=j7,d=CHa(a,String(b));g.ob(c)?DHa(d):(AHa(c),g.Gb(c,function(e){e(d)}))},zHa=function(){j7||(j7=g.Na("yt.mdx.remote.debug.handlers_")||[],g.Ia("yt.mdx.remote.debug.handlers_",j7,void 0))},DHa=function(a){var b=(l7+1)%50;
l7=b;m7[b]=a;n7||(n7=49==b)},AHa=function(a){var b=m7;
if(b[0]){var c=l7,d=n7?c:-1;do{d=(d+1)%50;var e=b[d];g.Gb(a,function(f){f(e)})}while(d!=c);
m7=Array(50);l7=-1;n7=!1}},CHa=function(a,b){var c=(g.A()-EHa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},o7=function(a){g.P.call(this);
this.I=a;this.screens=[]},FHa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},GHa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Ke(a.screens,function(f){return!!l6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=FHa(a,b[d])||c;return c},HHa=function(a,b){var c=a.screens.length;
a.screens=g.Ke(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},p7=function(a,b,c,d){g.P.call(this);
this.I=a;this.F=b;this.C=c;this.D=d;this.B=0;this.u=null;this.Ua=NaN},r7=function(a){o7.call(this,"LocalScreenService");
this.B=a;this.u=NaN;q7(this);this.info("Initializing with "+j6(this.screens))},IHa=function(a){if(a.screens.length){var b=g.Pc(a.screens,function(d){return d.id}),c=h7(a.B,"/pairing/get_lounge_token_batch");
i7(a.B,c,{screen_ids:b.join(",")},(0,g.z)(a.NI,a),(0,g.z)(a.MI,a))}},q7=function(a){if(g.uo("deprecate_pair_servlet_enabled"))return GHa(a,[]);
var b=qGa(wGa());b=g.Ke(b,function(c){return!c.uuid});
return GHa(a,b)},s7=function(a,b){yGa(g.Pc(a.screens,oGa));
b&&xGa()},u7=function(a,b){g.P.call(this);
this.I=b;var c=g.Ss("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.I(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.nb(c,l)}this.u=d;this.F=a;this.C=this.D=NaN;this.B=null;t7("Initialized with "+g.Fj(this.u))},JHa=function(a,b,c){var d=h7(a.F,"/pairing/get_screen_availability");
i7(a.F,d,{lounge_token:b.token},(0,g.z)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},v7=function(a,b){a:if(c6(b)!=c6(a.u))var c=!1;
else{c=g.Qb(b);for(var d=0,e=c.length;d<e;++d)if(!a.u[c[d]]){c=!1;break a}c=!0}c||(t7("Updated online screens: "+g.Fj(a.u)),a.u=b,a.W("screenChange"));KHa(a)},w7=function(a){isNaN(a.C)||g.Io(a.C);
a.C=g.Fo((0,g.z)(a.by,a),0<a.D&&a.D<g.A()?2E4:1E4)},t7=function(a){k7("OnlineScreenService",a)},LHa=function(a){var b={};
g.Gb(a.I(),function(c){c.token?b[c.token]=c.id:this.Sc("Requesting availability of screen w/o lounge token.")});
return b},KHa=function(a){a=g.Qb(g.Kb(a.u,function(b){return b}));
g.Cb(a);a.length?g.Rs("yt-remote-online-screen-ids",a.join(","),60):g.Ts("yt-remote-online-screen-ids")},x7=function(a){o7.call(this,"ScreenService");
this.F=a;this.u=this.B=null;this.C=[];this.D={};MHa(this)},OHa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var h=a.Pf();if(h=(c?m6(h,c):null)||m6(h,b)){h.uuid=b;var l=y7(a,h);JHa(a.u,l,function(m){e(m?l:null)})}else c?NHa(a,c,(0,g.z)(function(m){var n=y7(this,new g6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));JHa(this.u,n,function(p){e(p?n:null)})},a),f):e(null)},PHa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},NHa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Xb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.oq(h7(a.F,"/pairing/get_lounge_token_batch"),e)},QHa=function(a){a.screens=a.B.Pf();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.screens))},MHa=function(a){z7(a);
a.B=new r7(a.F);a.B.subscribe("screenChange",(0,g.z)(a.VI,a));QHa(a);a.C=qGa(g.Ss("yt-remote-automatic-screen-cache")||[]);z7(a);a.info("Initializing automatic screens: "+j6(a.C));a.u=new u7(a.F,(0,g.z)(a.Pf,a,!0));a.u.subscribe("screenChange",(0,g.z)(function(){this.W("onlineScreenChange")},a))},y7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.Rs("yt-remote-automatic-screen-cache",g.Pc(a.C,oGa)));z7(a);a.D[b.uuid]=b.id;g.Rs("yt-remote-device-id-map",a.D,31536E3);return b},z7=function(a){a.D=g.Ss("yt-remote-device-id-map")||{}},A7=function(a,b,c){g.P.call(this);
this.Y=c;this.P=a;this.u=b;this.K=null},B7=function(a,b){k7(a.Y,b)},C7=function(a,b){A7.call(this,a,b,"CastSession");
this.B=null;this.C=0;this.F=(0,g.z)(this.qR,this);this.D=(0,g.z)(this.IP,this);this.C=g.Fo((0,g.z)(function(){RHa(this,null)},this),12E4)},SHa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Fj(void 0));
var b={type:"getMdxSessionStatus"};a.B?a.B.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Oa,(0,g.z)(function(){B7(this,"Failed to send message: getMdxSessionStatus.")},a)):B7(a,"Sending yt message without session: "+g.Fj(b))},RHa=function(a,b){g.Io(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.getScreen()||a.getScreen().id!=b){var c=(0,g.z)(a.wt,a),d=(0,g.z)(a.Vf,a);a.zB(b,c,d,5)}}else a.Vf(Error("Waiting for session status timed out."))},D7=function(a,b,c){A7.call(this,a,b,"DialSession");
this.C=this.I=null;this.N="";this.ba=c;this.V=null;this.F=g.Oa;this.D=NaN;this.X=(0,g.z)(this.tR,this);this.B=g.Oa},THa=function(a){a.B=a.P.HG(a.N,a.u.label,a.u.friendlyName,(0,g.z)(function(b){this.B=g.Oa;
this.wt(b)},a),(0,g.z)(function(b){this.B=g.Oa;
this.Vf(b)},a))},UHa=function(a){var b={};
b.pairingCode=a.N;b.theme=a.ba;AGa()&&(b.env_useStageMdx=1);return g.Hd(b)},E7=function(a,b){A7.call(this,a,b,"ManualSession");
this.B=g.Fo((0,g.z)(this.Um,this,null),150)},F7=function(a,b,c,d){g.P.call(this);
this.B=a;this.K=b||"233637DE";this.I=c||"cl";this.P=d||!1;this.u=null;this.F=!1;this.C=[];this.D=(0,g.z)(this.zO,this)},VHa=function(a,b){return b?g.jb(a.C,function(c){return h6(b,c.label)},a):null},G7=function(a){k7("Controller",a)},yHa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},H7=function(a){return a.F||!!a.C.length||!!a.u},I7=function(a,b,c){b!=a.u&&(g.eg(a.u),(a.u=b)?(c?a.W("yt-remote-cast2-receiver-resumed",b.u):a.W("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.z)(a.vE,a,b)),b.getScreen()?a.W("yt-remote-cast2-session-change",b.getScreen()):c&&a.u.Um(null)):a.W("yt-remote-cast2-session-change",null))},WHa=function(a){var b=a.B.GG(),c=a.u&&a.u.u;
a=g.Pc(b,function(d){c&&h6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=VHa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},bIa=function(a,b,c,d,e,f,h){XHa()?YHa(b,e,f,h)&&(K7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?ZHa(a,c):(window.__onGCastApiAvailable=function(l,m){l?ZHa(a,c):(L7("Failed to load cast API: "+m),M7(!1),K7(!1),g.Ts("yt-remote-cast-available"),g.Ts("yt-remote-cast-receiver"),$Ha(),c(!1))},d?g.So("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?HGa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?u6():(GGa(),t6(aIa.map(EGa))))):J7("Cannot initialize because not running Chrome")},$Ha=function(){J7("dispose");
var a=N7();a&&a.dispose();g.Ia("yt.mdx.remote.cloudview.instance_",null,void 0);cIa(!1);g.Oo(O7);O7.length=0},P7=function(){return!!g.Ss("yt-remote-cast-installed")},dIa=function(){var a=g.Ss("yt-remote-cast-receiver");
return a?a.friendlyName:null},eIa=function(){J7("clearCurrentReceiver");
g.Ts("yt-remote-cast-receiver")},fIa=function(){return P7()?N7()?N7().getCastSession():(L7("getCastSelector: Cast is not initialized."),null):(L7("getCastSelector: Cast API is not installed!"),null)},R7=function(){P7()?N7()?Q7()?(J7("Requesting cast selector."),N7().requestSession()):(J7("Wait for cast API to be ready to request the session."),O7.push(g.No("yt-remote-cast2-api-ready",R7))):L7("requestCastSelector: Cast is not initialized."):L7("requestCastSelector: Cast API is not installed!")},S7=
function(a,b){Q7()?N7().setConnectedScreenStatus(a,b):L7("setConnectedScreenStatus called before ready.")},XHa=function(){var a=0<=g.Vc.search(/ (CrMo|Chrome|CriOS)\//);
return g.aB||a},gIa=function(a,b){N7().init(a,b)},YHa=function(a,b,c,d){var e=!1;
N7()||(a=new F7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Rs("yt-remote-cast-available",f);e6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){J7("onReceiverSelected: "+f.friendlyName);
g.Rs("yt-remote-cast-receiver",f);e6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){J7("onReceiverResumed: "+f.friendlyName);
g.Rs("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){J7("onSessionChange: "+i6(f));
f||g.Ts("yt-remote-cast-receiver");e6("yt-remote-cast2-session-change",f)}),g.Ia("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
J7("cloudview.createSingleton_: "+e);return e},N7=function(){return g.Na("yt.mdx.remote.cloudview.instance_")},ZHa=function(a,b){M7(!0);
K7(!1);gIa(a,function(c){c?(cIa(!0),g.Po("yt-remote-cast2-api-ready")):(L7("Failed to initialize cast API."),M7(!1),g.Ts("yt-remote-cast-available"),g.Ts("yt-remote-cast-receiver"),$Ha());b(c)})},J7=function(a){k7("cloudview",a)},L7=function(a){k7("cloudview",a)},M7=function(a){J7("setCastInstalled_ "+a);
g.Rs("yt-remote-cast-installed",a)},Q7=function(){return!!g.Na("yt.mdx.remote.cloudview.apiReady_")},cIa=function(a){J7("setApiReady_ "+a);
g.Ia("yt.mdx.remote.cloudview.apiReady_",a,void 0)},K7=function(a){g.Ia("yt.mdx.remote.cloudview.initializing_",a,void 0)},T7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.I=this.K=0;this.u=null;this.hasNext=this.Qh=!1;this.N=this.P=this.B=this.F=0;this.D=NaN;this.C=!1;this.reset(a)},U7=function(a){a.audioTrackId=null;
a.u=null;a.playerState=-1;a.Qh=!1;a.hasNext=!1;a.K=0;a.I=g.A();a.F=0;a.B=0;a.P=0;a.N=0;a.D=NaN;a.C=!1},V7=function(a){return a.Cb()?(g.A()-a.I)/1E3:0},W7=function(a,b){a.K=b;
a.I=g.A()},X7=function(a){switch(a.playerState){case 1:case 1081:return(g.A()-a.I)/1E3+a.K;
case -1E3:return 0}return a.K},Y7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&U7(a)},Z7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.$b(a.u);b.hasPrevious=a.Qh;b.hasNext=a.hasNext;b.playerTime=a.K;b.playerTimeAt=a.I;b.seekableStart=a.F;b.seekableEnd=a.B;b.duration=a.P;b.loadedTime=a.N;b.liveIngestionTime=a.D;return b},a8=function(a,b){g.P.call(this);
this.Ca=0;this.C=a;this.F=[];this.D=new tHa;this.B=this.u=null;this.P=(0,g.z)(this.JM,this);this.I=(0,g.z)(this.wp,this);this.K=(0,g.z)(this.IM,this);this.N=(0,g.z)(this.SM,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.fz,this),hIa(this))):c=3;0!=c&&(b?this.fz(c):g.Fo((0,g.z)(function(){this.fz(c)},this),0));
var d=fIa();d&&$7(this,d);this.subscribe("yt-remote-cast2-session-change",this.N)},b8=function(a){return new T7(a.C.getPlayerContextData())},hIa=function(a){g.Gb("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.C.subscribe(b,g.Wa(this.vO,b),this))},a)},iIa=function(a){g.Gb(a.F,function(b){this.C.unsubscribeByKey(b)},a);
a.F.length=0},c8=function(a,b){var c=a.D;
50>c.u.length+c.B.length&&a.D.B.push(b)},e8=function(a,b,c){var d=b8(a);
W7(d,c);-1E3!=d.playerState&&(d.playerState=b);d8(a,d)},f8=function(a,b,c){a.C.sendMessage(b,c)},d8=function(a,b){iIa(a);
a.C.setPlayerContextData(Z7(b));hIa(a)},$7=function(a,b){a.B&&(a.B.removeUpdateListener(a.P),a.B.removeMediaListener(a.I),a.wp(null));
a.B=b;a.B&&(k7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.P),a.B.addMediaListener(a.I),a.B.media.length&&a.wp(a.B.media[0]))},jIa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=b8(a);b.contentId!=d.videoId&&k7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;W7(d,a.u.getEstimatedTime());d8(a,d)}else k7("CP","No cast media video. Ignoring state update.")},g8=function(a,b,c){return(0,g.z)(function(d){this.Sc("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Sc("Retrying "+b+" using MDx browser channel."),f8(this,b,c))},a)},h8=function(a,b,c){g.P.call(this);
this.F=NaN;this.X=!1;this.P=this.K=this.N=this.V=NaN;this.Y=[];this.D=this.I=this.C=this.Ab=this.u=null;this.fa=a;this.Y.push(g.cp(window,"beforeunload",(0,g.z)(this.GI,this)));this.B=[];this.Ab=new T7;this.ba=b.id;this.u=kIa(this,c);this.u.subscribe("handlerOpened",this.OM,this);this.u.subscribe("handlerClosed",this.KM,this);this.u.subscribe("handlerError",this.LM,this);this.u.subscribe("handlerMessage",this.MM,this);xHa(this.u,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Ab.videoId;
g.Us()&&g.Rs("yt-remote-session-video-id",d)},this)},i8=function(a){k7("conn",a)},kIa=function(a,b){return new d7(h7(a.fa,"/bc"),b,!1,function(){return a.DG()})},j8=function(a,b){a.W("proxyStateChange",b)},lIa=function(a){a.F=g.Fo((0,g.z)(function(){i8("Connecting timeout");
this.xm(1)},a),2E4)},k8=function(a){g.Io(a.F);
a.F=NaN},l8=function(a){g.Io(a.V);
a.V=NaN},mIa=function(a){m8(a);
a.N=g.Fo((0,g.z)(function(){n8(this,"getNowPlaying")},a),2E4)},m8=function(a){g.Io(a.N);
a.N=NaN},oIa=function(a,b){b&&(k8(a),l8(a));
b==(f7(a.u)&&isNaN(a.F))?b&&(j8(a,1),n8(a,"getSubtitlesTrack")):b?(a.xB()&&a.Ab.reset(),j8(a,1),n8(a,"getNowPlaying"),nIa(a)):a.xm(1)},pIa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Ab.videoId&&(g.Wb(b.params)?a.Ab.u=null:a.Ab.u=b.params,a.W("remotePlayerChange"))},qIa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Ab.listId=b.params.listId||a.Ab.listId;Y7(a.Ab,c,d);a.W("remoteQueueChange")},sIa=function(a,b){b.params=b.params||{};
qIa(a,b);rIa(a,b);a.W("autoplayDismissed")},rIa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
W7(a.Ab,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Ab.playerState&&(c=-1E3);a.Ab.playerState=c;c=Number(b.params.loadedTime);a.Ab.N=isNaN(c)?0:c;c=Number(b.params.duration);a.Ab.P=isNaN(c)?0:c;c=a.Ab;var d=Number(b.params.liveIngestionTime);c.D=d;c.C=isNaN(d)?!1:!0;c=a.Ab;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.F=isNaN(d)?0:d;c.B=isNaN(e)?0:e;1==a.Ab.playerState?mIa(a):m8(a);a.W("remotePlayerChange")},tIa=function(a,b){if(-1E3!=
a.Ab.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Ab.playerState=c;c=parseInt(b.params.currentTime,10);W7(a.Ab,isNaN(c)?0:c);a.W("remotePlayerChange")}},uIa=function(a,b){var c="true"==b.params.muted;
a.Ab.volume=parseInt(b.params.volume,10);a.Ab.muted=c;a.W("remotePlayerChange")},vIa=function(a,b){a.I=b.params.videoId;
a.W("nowAutoplaying",parseInt(b.params.timeout,10))},wIa=function(a,b){var c="true"==b.params.hasNext;
a.Ab.Qh="true"==b.params.hasPrevious;a.Ab.hasNext=c;a.W("previousNextChange")},nIa=function(a){g.Io(a.P);
a.P=g.Fo((0,g.z)(a.xm,a,1),864E5)},n8=function(a,b,c){c?i8("Sending: action="+b+", params="+g.Fj(c)):i8("Sending: action="+b);
a.u.sendMessage(b,c)},o8=function(a){o7.call(this,"ScreenServiceProxy");
this.Ie=a;this.u=[];this.u.push(this.Ie.$_s("screenChange",(0,g.z)(this.oR,this)));this.u.push(this.Ie.$_s("onlineScreenChange",(0,g.z)(this.bO,this)))},BIa=function(a,b){b=g.L("MDX_CONFIG")||b;
sGa();q6();p8||(p8=new g7(b?b.loungeApiHost:void 0),AGa()&&(p8.u="/api/loungedev"));q8||(q8=g.Na("yt.mdx.remote.deferredProxies_")||[],g.Ia("yt.mdx.remote.deferredProxies_",q8,void 0));xIa();var c=r8();if(!c){var d=new x7(p8);g.Ia("yt.mdx.remote.screenService_",d,void 0);c=r8();var e=!1,f=void 0,h=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,h=b.theme,l=!!b.disableDial);bIa(a,d,function(m){m?s8()&&S7(s8(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){e6("yt-remote-receiver-availability-change")})},
e,f,h,l)}b&&!g.Na("yt.mdx.remote.initialized_")&&(g.Ia("yt.mdx.remote.initialized_",!0,void 0),t8("Initializing: "+g.Fj(b)),u8.push(g.No("yt-remote-cast2-availability-change",function(){e6("yt-remote-receiver-availability-change")})),u8.push(g.No("yt-remote-cast2-receiver-selected",function(){v8(null);
e6("yt-remote-auto-connect","cast-selector-receiver")})),u8.push(g.No("yt-remote-cast2-receiver-resumed",function(){e6("yt-remote-receiver-resumed","cast-selector-receiver")})),u8.push(g.No("yt-remote-cast2-session-change",yIa)),u8.push(g.No("yt-remote-connection-change",function(m){m?S7(s8(),"YouTube TV"):w8()||(S7(null,null),eIa())})),e=x8(),b.isAuto&&(e.id+="#dial"),g.uo("desktop_enable_autoplay")&&(e.capabilities=["atp"]),e.name=b.device,e.app=b.app,(h=b.theme)&&(e.theme=h),t8(" -- with channel params: "+
g.Fj(e)),zIa(e),c.start(),s8()||AIa())},DIa=function(){var a=CIa();
P7()&&g.Ss("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},CIa=function(){var a=r8().Ie.$_gos();
var b=y8();b&&z8()&&(l6(a,b)||a.push(b));return rGa(a)},A8=function(){var a=EIa();
!a&&P7()&&dIa()&&(a={key:"cast-selector-receiver",name:dIa()});return a},EIa=function(){var a=CIa(),b=y8();
b||(b=w8());return g.jb(a,function(c){return b&&h6(b,c.key)?!0:!1})},y8=function(){var a=s8();
if(!a)return null;var b=r8().Pf();return m6(b,a)},yIa=function(a){t8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=y8();b&&b.id==a.id?S7(b.id,"YouTube TV"):(b&&B8(),C8(a,1))}else z8()&&B8()},B8=function(){Q7()?N7().stopSession():L7("stopSession called before API ready.");
var a=z8();a&&(a.disconnect(1),D8(null))},E8=function(){var a=z8();
return!!a&&3!=a.getProxyState()},t8=function(a){k7("remote",a)},r8=function(){if(!F8){var a=g.Na("yt.mdx.remote.screenService_");
F8=a?new o8(a):null}return F8},s8=function(){return g.Na("yt.mdx.remote.currentScreenId_")},FIa=function(a){g.Ia("yt.mdx.remote.currentScreenId_",a,void 0)},GIa=function(){return g.Na("yt.mdx.remote.connectData_")},v8=function(a){g.Ia("yt.mdx.remote.connectData_",a,void 0)},z8=function(){return g.Na("yt.mdx.remote.connection_")},D8=function(a){var b=z8();
v8(null);a||FIa("");g.Ia("yt.mdx.remote.connection_",a,void 0);q8&&(g.Gb(q8,function(c){c(a)}),q8.length=0);
b&&!a?e6("yt-remote-connection-change",!1):!b&&a&&e6("yt-remote-connection-change",!0)},w8=function(){var a=g.Us();
if(!a)return null;var b=r8();if(!b)return null;b=b.Pf();return m6(b,a)},C8=function(a,b){s8();
y8()&&y8();if(G8)H8=a;else{FIa(a.id);var c=new h8(p8,a,x8());c.connect(b,GIa());c.subscribe("beforeDisconnect",function(d){e6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){z8()&&(z8(),D8(null))});
D8(c)}},AIa=function(){var a=w8();
a?(t8("Resume connection to: "+i6(a)),C8(a,0)):(r6(),eIa(),t8("Skipping connecting because no session screen found."))},xIa=function(){var a=x8();
if(g.Wb(a)){a=p6();var b=g.Ss("yt-remote-session-name")||"",c=g.Ss("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ia("yt.mdx.remote.channelParams_",a,void 0)}},x8=function(){return g.Na("yt.mdx.remote.channelParams_")||{}},zIa=function(a){a?(g.Rs("yt-remote-session-app",a.app),g.Rs("yt-remote-session-name",a.name)):(g.Ts("yt-remote-session-app"),g.Ts("yt-remote-session-name"));
g.Ia("yt.mdx.remote.channelParams_",a,void 0)},I8=function(a,b,c){g.B.call(this);
var d=this;this.B=a;this.J=b;this.rb=c;this.events=new g.Rr(this);this.V=this.events.R(this.J,"onVolumeChange",this.XD);this.F=!1;this.suggestion=null;this.I=new g.OK(64);this.u=new g.H(this.KF,500,this);this.C=new g.H(this.LF,1E3,this);this.P=new v6(this.TQ,0,this);this.D={};this.N=new g.H(this.nG,1E3,this);this.K=new w6(this.seekTo,1E3,this);this.X=g.Oa;g.C(this,this.events);this.events.R(b,"onCaptionsTrackListChanged",this.EN);this.events.R(b,"captionschanged",this.GM);this.events.R(b,"captionssettingschanged",
this.OF);this.events.R(b,"videoplayerreset",this.xt);this.events.R(b,"mdxautoplaycancel",function(){d.rb.NA()});
a=this.rb;a.la();a.subscribe("proxyStateChange",this.qE,this);a.subscribe("remotePlayerChange",this.Cp,this);a.subscribe("remoteQueueChange",this.xt,this);a.subscribe("previousNextChange",this.mE,this);a.subscribe("nowAutoplaying",this.hE,this);a.subscribe("autoplayDismissed",this.ID,this);g.C(this,this.u);g.C(this,this.C);g.C(this,this.P);g.C(this,this.N);g.C(this,this.K);this.OF();this.xt();this.Cp()},HIa=function(a){a.Dc(0);
a.u.stop();a.Ad(new g.OK(64))},K8=function(a,b){if(J8(a)&&!a.F){var c=null;
b&&(c={style:a.J.getSubtitlesUserSettings()},g.bc(c,b));a.rb.EG(a.J.getVideoData(1).videoId,c);a.D=b8(a.rb).u}},L8=function(a,b){var c=a.J.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.J.getVideoData(1);a.rb.playVideo(c.videoId,b,d,e,c.playerParams,c.og,eGa(c));a.Ad(new g.OK(1))},IIa=function(a,b){if(b){var c=a.J.getOption("captions","tracklist",{WB:1});
c&&c.length?(a.J.setOption("captions","track",b),a.F=!1):(a.J.loadModule("captions"),a.F=!0)}else a.J.setOption("captions","track",{})},J8=function(a){return b8(a.rb).videoId===a.J.getVideoData(1).videoId},M8=function(){g.V.call(this,{G:"div",
L:"ytp-mdx-manual-pairing-popup-dialog",U:{role:"dialog"},S:[{G:"div",L:"ytp-mdx-manual-pairing-popup-dialog-inner-content",S:[{G:"div",L:"ytp-mdx-manual-pairing-popup-title",Z:"Pronto dejar\u00e1 de ser posible establecer una conexi\u00f3n web con una TV mediante un c\u00f3digo"},{G:"div",L:"ytp-mdx-manual-pairing-popup-buttons",S:[{G:"button",ia:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],Z:"M\u00e1s informaci\u00f3n"},{G:"button",ia:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],
Z:"Aceptar"}]}]}]});this.u=new g.yN(this,250);this.learnMoreButton=this.ga("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.ga("ytp-mdx-manual-pairing-popup-ok");g.C(this,this.u);this.R(this.learnMoreButton,"click",this.B);this.R(this.okButton,"click",this.C)},N8=function(){g.V.call(this,{G:"div",
L:"ytp-mdx-popup-dialog",U:{role:"dialog"},S:[{G:"div",L:"ytp-mdx-popup-dialog-inner-content",S:[{G:"div",L:"ytp-mdx-popup-title",Z:"No has iniciado sesi\u00f3n"},{G:"div",L:"ytp-mdx-popup-description",Z:"Los v\u00eddeos que veas podr\u00edan aparecer en el historial de reproducciones de la TV e influir en las recomendaciones. Puedes evitarlo si cancelas e inicias sesi\u00f3n en YouTube desde tu ordenador."},{G:"div",L:"ytp-mdx-privacy-popup-buttons",S:[{G:"button",ia:["ytp-button","ytp-mdx-privacy-popup-cancel"],
Z:"Cancelar"},{G:"button",ia:["ytp-button","ytp-mdx-privacy-popup-confirm"],Z:"Confirmar"}]}]}]});this.u=new g.yN(this,250);this.cancelButton=this.ga("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.ga("ytp-mdx-privacy-popup-confirm");g.C(this,this.u);this.R(this.cancelButton,"click",this.B);this.R(this.confirmButton,"click",this.C)},O8=function(a){g.V.call(this,{G:"div",
L:"ytp-remote",S:[{G:"div",L:"ytp-remote-display-status",S:[{G:"div",L:"ytp-remote-display-status-icon",S:[g.SM()]},{G:"div",L:"ytp-remote-display-status-text",Z:"{{statustext}}"}]}]});this.api=a;this.u=new g.yN(this,250);g.C(this,this.u);this.R(a,"presentingplayerstatechange",this.B);JIa(this,g.iI(a))},JIa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.T(b,128)?g.bJ("No se ha podido reproducir el v\u00eddeo en $RECEIVER_NAME",c):b.Cb()||g.T(b,4)?g.bJ("El v\u00eddeo se est\u00e1 reproduciendo en $RECEIVER_NAME",c):g.bJ("Conectado a $RECEIVER_NAME",c);a.ua("statustext",c);a.u.show()}else a.u.hide()},P8=function(a,b){g.IZ.call(this,"Reproducir en",0,a,b);
this.J=a;this.tk={};this.R(a,"onMdxReceiversChange",this.D);this.R(a,"presentingplayerstatechange",this.D);this.D()},Q8=function(a){g.uS.call(this,a);
this.Zg={key:k6(),name:"Este ordenador"};this.Dh=null;this.subscriptions=[];this.Nx=this.rb=null;this.tk=[this.Zg];this.Kj=this.Zg;this.xc=new g.OK(64);this.qC=0;this.Vd=-1;this.Wm=null;this.Fp=this.Es=!1;this.Ll=this.pn=null;if(!g.YB(this.player.T())){a=this.player;var b=g.GW(a);b&&(b=b.jl())&&(b=new P8(a,b),g.C(this,b));b=new O8(a);g.C(this,b);g.cP(a,b.element,4);this.pn=new N8;g.C(this,this.pn);g.cP(a,this.pn.element,4);g.R(this.player.T().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.R(this.player.T().experiments,"deprecate_pair_servlet_enabled")&&(this.Wm=new M8,g.C(this,this.Wm),g.cP(a,this.Wm.element,4));this.Fp=!!w8();this.Es=!!g.Ss("yt-remote-manual-pairing-warning-shown")}},R8=function(a){a.Ll&&(a.player.removeEventListener("presentingplayerstatechange",a.Ll),a.Ll=null)},KIa=function(a,b,c){a.xc=c;
a.player.W("presentingplayerstatechange",new g.qI(c,b))},LIa=function(a,b,c){var d=!1;
1===b?d=!a.Fp:2===b&&(d=!a.Es);d&&g.sI(c,8)&&(a.player.pauseVideo(),R8(a))},S8=function(a,b){if(b.key!==a.Kj.key)if(b.key===a.Zg.key)B8();
else{if(a.Wm&&!a.Es&&b!==a.Zg&&"cast-selector-receiver"!==b.key&&g.hC(a.player.T()))MIa(a);else{var c;(c=!g.R(a.player.T().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.L("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.L("SESSION_INDEX")&&!g.L("LOGGED_IN")))||a.Fp||!a.pn);(c?0:g.hC(a.player.T())||g.lC(a.player.T()))&&NIa(a)}a.Kj=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.R(a.player.T().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.getLength();l++)h[l]=f.Ja(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.og,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=eGa(c))&&(d.locationInfo=c);c=d}t8("Connecting to: "+g.Fj(b));"cast-selector-receiver"==b.key?(v8(c||null),c=
c||null,Q7()?N7().setLaunchParams(c):L7("setLaunchParams called before ready.")):!c&&E8()&&s8()==b.key?e6("yt-remote-connection-change",!0):(B8(),v8(c||null),c=r8().Pf(),(c=m6(c,b.key))&&C8(c,1))}},NIa=function(a){g.iI(a.player).Cb()?a.player.pauseVideo():(a.Ll=function(b){LIa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.Ll));
a.pn&&a.pn.oc();z8()||(G8=!0)},MIa=function(a){g.iI(a.player).Cb()?a.player.pauseVideo():(a.Ll=function(b){LIa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.Ll));
a.Wm&&a.Wm.oc();z8()||(G8=!0)},SGa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},L6={"'":"\\'"},OIa={},nGa={UR:"atp",SU:"ska",DU:"que",ST:"mus",RU:"sus",SS:"dsp",KU:"seq"},s6,o6="",FGa=BGa("loadCastFramework")||BGa("loadCastApplicationFramework"),aIa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ya(v6,g.B);g.k=v6.prototype;g.k.CI=function(a){this.D=arguments;this.u=!1;this.Ua?this.C=g.A()+this.Ke:this.Ua=g.Um(this.F,this.Ke)};
g.k.stop=function(){this.Ua&&(g.v.clearTimeout(this.Ua),this.Ua=null);this.C=null;this.u=!1;this.D=[]};
g.k.pause=function(){++this.B};
g.k.resume=function(){this.B&&(--this.B,!this.B&&this.u&&(this.u=!1,this.I.apply(null,this.D)))};
g.k.aa=function(){this.stop();v6.Vc.aa.call(this)};
g.k.DI=function(){this.C?(this.Ua=g.Um(this.F,this.C-g.A()),this.C=null):(this.Ua=null,this.B?this.u=!0:(this.u=!1,this.I.apply(null,this.D)))};g.u(w6,g.B);g.k=w6.prototype;g.k.GC=function(a){this.C=arguments;this.Ua||this.B?this.u=!0:x6(this)};
g.k.stop=function(){this.Ua&&(g.v.clearTimeout(this.Ua),this.Ua=null,this.u=!1,this.C=null)};
g.k.pause=function(){this.B++};
g.k.resume=function(){this.B--;this.B||!this.u||this.Ua||(this.u=!1,x6(this))};
g.k.aa=function(){g.B.prototype.aa.call(this);this.stop()};z6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
z6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};var B6=new g.im;g.u(IGa,g.Ll);D6.prototype.u=null;D6.prototype.getOptions=function(){var a;(a=this.u)||(a={},KGa(this)&&(a[0]=!0,a[1]=!0),a=this.u=a);return a};var T8;g.Ya(JGa,D6);T8=new JGa;g.k=E6.prototype;g.k.nl=null;g.k.ph=!1;g.k.In=null;g.k.bz=null;g.k.un=null;g.k.Cn=null;g.k.Fj=null;g.k.uk=null;g.k.Ml=null;g.k.Nd=null;g.k.rq=0;g.k.wh=null;g.k.pu=null;g.k.Tj=null;g.k.Ho=-1;g.k.AF=!0;g.k.Pk=!1;g.k.rw=0;g.k.Ht=null;var PGa={},H6={};g.k=E6.prototype;g.k.setTimeout=function(a){this.F=a};
g.k.bQ=function(a){a=a.target;var b=this.Ht;b&&3==Q6(a)?b.GC():this.AG(a)};
g.k.AG=function(a){try{if(a==this.Nd)a:{var b=Q6(this.Nd),c=this.Nd.I,d=this.Nd.getStatus();if(g.ye&&!g.ae(10)||g.Ae&&!g.$d("420+")){if(4>b)break a}else if(3>b||3==b&&!g.rg&&!S6(this.Nd))break a;this.Pk||4!=b||7==c||(8==c||0>=d?this.u.hh(3):this.u.hh(2));M6(this);var e=this.Nd.getStatus();this.Ho=e;var f=S6(this.Nd);(this.ph=200==e)?(4==b&&J6(this),this.I?(QGa(this,b,f),g.rg&&this.ph&&3==b&&(this.D.ra(this.C,"tick",this.VP),this.C.start())):I6(this,f),this.ph&&!this.Pk&&(4==b?this.u.Sr(this):(this.ph=
!1,G6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Tj=3,C6(13)):(this.Tj=0,C6(14)),J6(this),K6(this))}}catch(h){this.Nd&&S6(this.Nd)}finally{}};
g.k.VP=function(){var a=Q6(this.Nd),b=S6(this.Nd);this.rq<b.length&&(M6(this),QGa(this,a,b),this.ph&&4!=a&&G6(this))};
g.k.pP=function(a){A6((0,g.z)(this.oP,this,a),0)};
g.k.oP=function(a){this.Pk||(M6(this),I6(this,a),G6(this))};
g.k.zE=function(a){A6((0,g.z)(this.nP,this,a),0)};
g.k.nP=function(a){this.Pk||(J6(this),this.ph=a,this.u.Sr(this),this.u.hh(4))};
g.k.cancel=function(){this.Pk=!0;J6(this)};
g.k.BP=function(){this.In=null;var a=g.A();0<=a-this.bz?(2!=this.Cn&&this.u.hh(3),J6(this),this.Tj=2,C6(18),K6(this)):UGa(this,this.bz-a)};
g.k.getLastError=function(){return this.Tj};g.Ya(O6,g.im);var aHa=/^https?$/i,PIa=["POST","PUT"];g.k=O6.prototype;
g.k.send=function(a,b,c,d){if(this.u)throw Error("[goog.net.XhrIo] Object is active with another request="+this.N+"; newUri="+a);b=b?b.toUpperCase():"GET";this.N=a;this.D="";this.I=0;this.oa=b;this.fa=!1;this.B=!0;this.u=this.ba?LGa(this.ba):LGa(T8);this.Y=this.ba?this.ba.getOptions():T8.getOptions();this.u.onreadystatechange=(0,g.z)(this.nE,this);try{d6(R6(this,"Opening Xhr")),this.ha=!0,this.u.open(b,String(a),!0),this.ha=!1}catch(f){d6(R6(this,"Error opening Xhr: "+f.message));$Ga(this,f);return}a=
c||"";var e=this.headers.clone();d&&jGa(d,function(f,h){e.set(h,f)});
d=g.jb(e.lg(),YGa);c=g.v.FormData&&a instanceof g.v.FormData;!g.nb(PIa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.u.setRequestHeader(h,f)},this);
this.ya&&(this.u.responseType=this.ya);"withCredentials"in this.u&&this.u.withCredentials!==this.da&&(this.u.withCredentials=this.da);try{cHa(this),0<this.K&&(this.X=XGa(this.u),d6(R6(this,"Will abort after "+this.K+"ms if incomplete, xhr2 "+this.X)),this.X?(this.u.timeout=this.K,this.u.ontimeout=(0,g.z)(this.IB,this)):this.V=g.Um(this.IB,this.K,this)),d6(R6(this,"Sending request")),this.P=!0,this.u.send(a),this.P=!1}catch(f){d6(R6(this,"Send error: "+f.message)),$Ga(this,f)}};
g.k.IB=function(){"undefined"!=typeof g.$0&&this.u&&(this.D="Timed out after "+this.K+"ms, aborting",this.I=8,R6(this,this.D),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.u&&this.B&&(R6(this,"Aborting"),this.B=!1,this.F=!0,this.u.abort(),this.F=!1,this.I=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),P6(this))};
g.k.aa=function(){this.u&&(this.B&&(this.B=!1,this.F=!0,this.u.abort(),this.F=!1),P6(this,!0));O6.Vc.aa.call(this)};
g.k.nE=function(){this.la()||(this.ha||this.P||this.F?bHa(this):this.yO())};
g.k.yO=function(){bHa(this)};
g.k.isActive=function(){return!!this.u};
g.k.getStatus=function(){try{return 2<Q6(this)?this.u.status:-1}catch(a){return-1}};
g.k.getLastError=function(){return"string"===typeof this.D?this.D:String(this.D)};g.k=dHa.prototype;g.k.pw=null;g.k.If=null;g.k.It=!1;g.k.HB=null;g.k.ur=null;g.k.Vw=null;g.k.qw=null;g.k.Ca=null;g.k.Pi=-1;g.k.Go=null;g.k.ao=null;g.k.connect=function(a){this.qw=a;a=T6(this.u,null,this.qw);C6(3);this.HB=g.A();var b=this.u.K;null!=b?(this.Go=b[0],(this.ao=b[1])?(this.Ca=1,eHa(this)):(this.Ca=2,V6(this))):(b6(a,"MODE","init"),this.If=new E6(this,void 0,void 0,void 0),this.If.nl=this.pw,F6(this.If,a,!1,null,!0),this.Ca=0)};
g.k.EH=function(a){if(a)this.Ca=2,V6(this);else{C6(4);var b=this.u;b.Ph=b.Ij.Pi;b7(b,9)}a&&this.hh(2)};
g.k.Fv=function(a){return this.u.Fv(a)};
g.k.abort=function(){this.If&&(this.If.cancel(),this.If=null);this.Pi=-1};
g.k.GB=function(){return!1};
g.k.rE=function(a,b){this.Pi=a.Ho;if(0==this.Ca)if(b){try{var c=this.B.parse(b)}catch(d){c=this.u;c.Ph=this.Pi;b7(c,2);return}this.Go=c[0];this.ao=c[1]}else c=this.u,c.Ph=this.Pi,b7(c,2);else if(2==this.Ca)if(this.It)C6(7),this.Vw=g.A();else if("11111"==b){if(C6(6),this.It=!0,this.ur=g.A(),c=this.ur-this.HB,!g.ye||g.ae(10)||500>c)this.Pi=200,this.If.cancel(),C6(12),U6(this.u,this,!0)}else C6(8),this.ur=this.Vw=g.A(),this.It=!1};
g.k.Sr=function(){this.Pi=this.If.Ho;if(this.If.ph)0==this.Ca?this.ao?(this.Ca=1,eHa(this)):(this.Ca=2,V6(this)):2==this.Ca&&((!g.ye||g.ae(10)?!this.It:200>this.Vw-this.ur)?(C6(11),U6(this.u,this,!1)):(C6(12),U6(this.u,this,!0)));else{0==this.Ca?C6(9):2==this.Ca&&C6(10);var a=this.u;this.If.getLastError();a.Ph=this.Pi;b7(a,2)}};
g.k.Yp=function(){return this.u.Yp()};
g.k.isActive=function(){return this.u.isActive()};
g.k.hh=function(a){this.u.hh(a)};g.k=W6.prototype;g.k.Hm=null;g.k.vo=null;g.k.yf=null;g.k.md=null;g.k.ow=null;g.k.wr=null;g.k.kA=null;g.k.Rr=null;g.k.qp=0;g.k.VL=0;g.k.Ge=null;g.k.Mj=null;g.k.Ai=null;g.k.Vk=null;g.k.Ij=null;g.k.mu=null;g.k.Tm=-1;g.k.pC=-1;g.k.Ph=-1;g.k.Cm=0;g.k.lm=0;g.k.Qk=8;g.Ya(gHa,g.Ll);g.Ya(hHa,g.Ll);g.k=W6.prototype;g.k.connect=function(a,b,c,d,e){C6(0);this.ow=b;this.vo=c||{};d&&void 0!==e&&(this.vo.OSID=d,this.vo.OAID=e);this.F?(A6((0,g.z)(this.AA,this,a),100),lHa(this)):this.AA(a)};
g.k.AA=function(a){this.Ij=new dHa(this);this.Ij.pw=this.Hm;this.Ij.B=this.D;this.Ij.connect(a)};
g.k.GB=function(){return 0==this.Ca};
g.k.yE=function(a){this.Mj=null;oHa(this,a)};
g.k.xE=function(){this.Ai=null;this.md=new E6(this,this.B,"rpc",this.I);this.md.nl=this.Hm;this.md.rw=0;var a=this.kA.clone();$5(a,"RID","rpc");$5(a,"SID",this.B);$5(a,"CI",this.mu?"0":"1");$5(a,"AID",this.Tm);X6(this,a);if(!g.ye||g.ae(10))$5(a,"TYPE","xmlhttp"),F6(this.md,a,!0,this.Rr,!1);else{$5(a,"TYPE","html");var b=this.md,c=!!this.Rr;b.Cn=3;b.Fj=a6(a.clone());TGa(b,c)}};
g.k.rE=function(a,b){if(0!=this.Ca&&(this.md==a||this.yf==a))if(this.Ph=a.Ho,this.yf==a&&3==this.Ca)if(7<this.Qk){try{var c=this.D.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Ai){if(this.md)if(this.md.un+3E3<this.yf.un)Z6(this),this.md.cancel(),this.md=null;else break a;a7(this);C6(19)}}else this.pC=c[1],0<this.pC-this.Tm&&37500>c[2]&&this.mu&&0==this.lm&&!this.Vk&&(this.Vk=A6((0,g.z)(this.AM,this),6E3));else b7(this,11)}else b!=OIa.rS.u&&b7(this,11);else if(this.md==
a&&Z6(this),!g.sc(b)){c=this.D.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.Tm=e[0];e=e[1];2==this.Ca?"c"==e[0]?(this.B=e[1],this.Rr=e[2],e=e[3],null!=e?this.Qk=e:this.Qk=6,this.Ca=3,this.Ge&&this.Ge.wA(),this.kA=T6(this,this.Yp()?this.Rr:null,this.ow),pHa(this)):"stop"==e[0]&&b7(this,7):3==this.Ca&&("stop"==e[0]?b7(this,7):"noop"!=e[0]&&this.Ge&&this.Ge.vA(e),this.lm=0)}}};
g.k.AM=function(){null!=this.Vk&&(this.Vk=null,this.md.cancel(),this.md=null,a7(this),C6(20))};
g.k.Sr=function(a){if(this.md==a){Z6(this);this.md=null;var b=2}else if(this.yf==a)this.yf=null,b=1;else return;this.Ph=a.Ho;if(0!=this.Ca)if(a.ph)1==b?(b=B6,b.dispatchEvent(new gHa(b,a.Ml?a.Ml.length:0,g.A()-a.un,this.Cm)),Y6(this),this.C.length=0):pHa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ph)){if(d=1==b)this.yf||this.Mj||1==this.Ca||2<=this.Cm?d=!1:(this.Mj=A6((0,g.z)(this.yE,this,a),qHa(this,this.Cm)),this.Cm++,d=!0);d=!(d||2==b&&a7(this))}if(d)switch(c){case 1:b7(this,
5);break;case 4:b7(this,10);break;case 3:b7(this,6);break;case 7:b7(this,12);break;default:b7(this,2)}}};
g.k.aI=function(a){if(!g.nb(arguments,this.Ca))throw Error("Unexpected channel state: "+this.Ca);};
g.k.HQ=function(a){a?C6(2):(C6(1),rHa(this,8))};
g.k.Fv=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new O6;a.da=!1;return a};
g.k.isActive=function(){return!!this.Ge&&this.Ge.isActive(this)};
g.k.hh=function(a){var b=B6;b.dispatchEvent(new hHa(b,a))};
g.k.Yp=function(){return!(!g.ye||g.ae(10))};
g.k=sHa.prototype;g.k.wA=function(){};
g.k.vA=function(){};
g.k.uA=function(){};
g.k.qv=function(){};
g.k.hB=function(){return{}};
g.k.isActive=function(){return!0};g.k=tHa.prototype;g.k.isEmpty=function(){return g.ob(this.u)&&g.ob(this.B)};
g.k.clear=function(){this.u=[];this.B=[]};
g.k.contains=function(a){return g.nb(this.u,a)||g.nb(this.B,a)};
g.k.remove=function(a){var b=this.u;var c=(0,g.cAa)(b,a);0<=c?(g.qb(b,c),b=!0):b=!1;return b||g.rb(this.B,a)};
g.k.Ye=function(){for(var a=[],b=this.u.length-1;0<=b;--b)a.push(this.u[b]);var c=this.B.length;for(b=0;b<c;++b)a.push(this.B[b]);return a};g.Ya(c7,g.B);g.k=c7.prototype;g.k.iP=function(){this.Ke=Math.min(3E5,2*this.Ke);this.C();this.B&&this.start()};
g.k.start=function(){var a=this.Ke+15E3*Math.random();this.u.ub(a);this.B=g.A()+a};
g.k.stop=function(){this.u.stop();this.B=0};
g.k.isActive=function(){return this.u.isActive()};
g.k.reset=function(){this.u.stop();this.Ke=5E3};g.Ya(d7,sHa);g.k=d7.prototype;g.k.subscribe=function(a,b,c){return this.C.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.C.unsubscribe(a,b,c)};
g.k.jk=function(a){return this.C.ol(a)};
g.k.W=function(a,b){return this.C.W.apply(this.C,arguments)};
g.k.dispose=function(){this.Bd||(this.Bd=!0,g.eg(this.C),wHa(this),g.eg(this.B),this.B=null,this.X=function(){return""})};
g.k.la=function(){return this.Bd};
g.k.connect=function(a,b,c){if(!this.u||2!=this.u.Ca){this.N="";this.B.stop();this.F=a||null;this.D=b||0;a=this.V+"/test";b=this.V+"/bind";var d=new W6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.Y),e=this.u;e&&(e.Ge=null);d.Ge=this;this.u=d;e7(this);e?this.u.connect(a,b,this.I,e.B,e.Tm):c?this.u.connect(a,b,this.I,c.sessionId,c.arrayId):this.u.connect(a,b,this.I)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.bc(c,b);this.B.isActive()||2==(this.u?this.u.Ca:0)?this.K.push(c):f7(this)&&(e7(this),mHa(this.u,c))};
g.k.wA=function(){this.B.reset();this.F=null;this.D=0;if(this.K.length){var a=this.K;this.K=[];for(var b=0,c=a.length;b<c;++b)mHa(this.u,a[b])}this.W("handlerOpened")};
g.k.uA=function(a){var b=2==a&&401==this.u.Ph;4==a||b||this.B.start();this.W("handlerError",a)};
g.k.qv=function(a){if(!this.B.isActive())this.W("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.K.push(d)}};
g.k.hB=function(){var a={v:2};this.N&&(a.gsessionid=this.N);0!=this.D&&(a.ui=""+this.D);0!=this.P&&(a.ui=""+this.P);this.F&&g.bc(a,this.F);return a};
g.k.vA=function(a){"S"==a[0]?this.N=a[1]:"gracefulReconnect"==a[0]?(this.B.start(),kHa(this.u)):this.W("handlerMessage",new uHa(a[0],a[1]))};
g.k.nQ=function(){this.B.isActive();var a=this.u,b=0;a.md&&b++;a.yf&&b++;0==b&&this.connect(this.F,this.D)};g7.prototype.D=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g7.prototype.C=function(a,b){a(Error("Request error: "+b.status))};
g7.prototype.F=function(a){a(Error("request timed out"))};var EHa=g.A(),j7=null,m7=Array(50),l7=-1,n7=!1;g.Ya(o7,g.P);o7.prototype.Pf=function(){return this.screens};
o7.prototype.contains=function(a){return!!l6(this.screens,a)};
o7.prototype.get=function(a){return a?m6(this.screens,a):null};
o7.prototype.info=function(a){k7(this.I,a)};g.u(p7,g.P);g.k=p7.prototype;g.k.start=function(){!this.u&&isNaN(this.Ua)&&this.FG()};
g.k.stop=function(){this.u&&(this.u.abort(),this.u=null);isNaN(this.Ua)||(g.Io(this.Ua),this.Ua=NaN)};
g.k.aa=function(){this.stop();g.P.prototype.aa.call(this)};
g.k.FG=function(){this.Ua=NaN;this.u=g.oq(h7(this.I,"/pairing/get_screen"),{method:"POST",Xb:{pairing_code:this.F},timeout:5E3,onSuccess:(0,g.z)(this.mR,this),onError:(0,g.z)(this.lR,this),Df:(0,g.z)(this.nR,this)})};
g.k.mR=function(a,b){this.u=null;var c=b.screen||{};c.dialId=this.C;c.name=this.D;this.W("pairingComplete",new g6(c))};
g.k.lR=function(a){this.u=null;a.status&&404==a.status?this.B>=QIa.length?this.W("pairingFailed",Error("DIAL polling timed out")):(a=QIa[this.B],this.Ua=g.Fo((0,g.z)(this.FG,this),a),this.B++):this.W("pairingFailed",Error("Server error "+a.status))};
g.k.nR=function(){this.u=null;this.W("pairingFailed",Error("Server not responding"))};
var QIa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ya(r7,o7);g.k=r7.prototype;g.k.start=function(){q7(this)&&this.W("screenChange");!g.Ss("yt-remote-lounge-token-expiration")&&IHa(this);g.Io(this.u);this.u=g.Fo((0,g.z)(this.start,this),1E4)};
g.k.add=function(a,b){q7(this);FHa(this,a);s7(this,!1);this.W("screenChange");b(a);a.token||IHa(this)};
g.k.remove=function(a,b){var c=q7(this);HHa(this,a)&&(s7(this,!1),c=!0);b(a);c&&this.W("screenChange")};
g.k.ku=function(a,b,c,d){var e=q7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,s7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.W("screenChange")};
g.k.aa=function(){g.Io(this.u);r7.Vc.aa.call(this)};
g.k.NI=function(a){q7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}s7(this,!b);b&&k7(this.I,"Missed "+b+" lounge tokens.")};
g.k.MI=function(a){k7(this.I,"Requesting lounge tokens failed: "+a)};g.u(u7,g.P);g.k=u7.prototype;g.k.start=function(){var a=parseInt(g.Ss("yt-remote-fast-check-period")||"0",10);(this.D=g.A()-144E5<a?0:a)?w7(this):(this.D=g.A()+3E5,g.Rs("yt-remote-fast-check-period",this.D),this.by())};
g.k.isEmpty=function(){return g.Wb(this.u)};
g.k.update=function(){t7("Updating availability on schedule.");var a=this.I(),b=g.Kb(this.u,function(c,d){return c&&!!m6(a,d)},this);
v7(this,b)};
g.k.aa=function(){g.Io(this.C);this.C=NaN;this.B&&(this.B.abort(),this.B=null);g.P.prototype.aa.call(this)};
g.k.by=function(){g.Io(this.C);this.C=NaN;this.B&&this.B.abort();var a=LHa(this);if(c6(a)){var b=h7(this.F,"/pairing/get_screen_availability");this.B=i7(this.F,b,{lounge_token:g.Qb(a).join(",")},(0,g.z)(this.TO,this,a),(0,g.z)(this.SO,this))}else v7(this,{}),w7(this)};
g.k.TO=function(a,b){this.B=null;var c=g.Qb(LHa(this));if(g.Eb(c,g.Qb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;v7(this,d);w7(this)}else this.Sc("Changing Screen set during request."),this.by()};
g.k.SO=function(a){this.Sc("Screen availability failed: "+a);this.B=null;w7(this)};
g.k.Sc=function(a){k7("OnlineScreenService",a)};g.Ya(x7,o7);g.k=x7.prototype;g.k.start=function(){this.B.start();this.u.start();this.screens.length&&(this.W("screenChange"),this.u.isEmpty()||this.W("onlineScreenChange"))};
g.k.add=function(a,b,c){this.B.add(a,b,c)};
g.k.remove=function(a,b,c){this.B.remove(a,b,c);this.u.update()};
g.k.ku=function(a,b,c,d){this.B.contains(a)?this.B.ku(a,b,c,d):(a="Updating name of unknown screen: "+a.name,k7(this.I,a),d(Error(a)))};
g.k.Pf=function(a){return a?this.screens:g.tb(this.screens,g.Ke(this.C,function(b){return!this.contains(b)},this))};
g.k.GG=function(){return g.Ke(this.Pf(!0),function(a){return!!this.u.u[a.id]},this)};
g.k.HG=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new p7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(h){g.eg(f);d(y7(this,h))},this));
f.subscribe("pairingFailed",function(h){g.eg(f);e(h)});
f.start();return(0,g.z)(f.stop,f)};
g.k.pR=function(a,b,c,d){g.oq(h7(this.F,"/pairing/get_screen"),{method:"POST",Xb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(e,f){var h=new g6(f.screen||{});if(!h.name||PHa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);PHa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(y7(this,h))},this),
onError:(0,g.z)(function(e){d(Error("pairing request failed: "+e.status))},this),
Df:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.k.aa=function(){g.eg(this.B);g.eg(this.u);x7.Vc.aa.call(this)};
g.k.VI=function(){QHa(this);this.W("screenChange");this.u.update()};
x7.prototype.dispose=x7.prototype.dispose;g.Ya(A7,g.P);g.k=A7.prototype;g.k.getScreen=function(){return this.K};
g.k.wt=function(a){this.K=a;this.W("sessionScreen",this.K)};
g.k.Vf=function(a){this.la()||(a&&B7(this,""+a),this.K=null,this.W("sessionScreen",null))};
g.k.info=function(a){k7(this.Y,a)};
g.k.JG=function(){return null};
g.k.my=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){B7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.aa=function(){this.my("");A7.Vc.aa.call(this)};g.u(C7,A7);g.k=C7.prototype;g.k.ly=function(a){if(this.B){if(this.B==a)return;B7(this,"Overriding cast sesison with new session object");this.B.removeUpdateListener(this.F);this.B.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.B=a;this.B.addUpdateListener(this.F);this.B.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);SHa(this)};
g.k.Um=function(a){this.info("launchWithParams no-op for Cast: "+g.Fj(a))};
g.k.stop=function(){this.B?this.B.stop((0,g.z)(function(){this.Vf()},this),(0,g.z)(function(){this.Vf(Error("Failed to stop receiver app."))},this)):this.Vf(Error("Stopping cast device witout session."))};
g.k.my=function(){};
g.k.aa=function(){this.info("disposeInternal");g.Io(this.C);this.C=0;this.B&&(this.B.removeUpdateListener(this.F),this.B.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.B=null;A7.prototype.aa.call(this)};
g.k.IP=function(a,b){if(!this.la())if(b){var c=y6(b);if(g.Sa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Fj(c));switch(d){case "mdxSessionStatus":RHa(this,c.screenId);break;default:B7(this,"Unknown youtube message: "+d)}}else B7(this,"Unable to parse message.")}else B7(this,"No data in message.")};
g.k.zB=function(a,b,c,d){OHa(this.P,this.u.label,a,this.u.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(B7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Fo((0,g.z)(this.zB,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.JG=function(){return this.B};
g.k.qR=function(a){this.la()||a||(B7(this,"Cast session died."),this.Vf())};g.u(D7,A7);g.k=D7.prototype;g.k.ly=function(a){this.C=a;this.C.addUpdateListener(this.X)};
g.k.Um=function(a){this.V=a;this.F()};
g.k.stop=function(){this.B();this.B=g.Oa;g.Io(this.D);this.C?this.C.stop((0,g.z)(this.Vf,this,null),(0,g.z)(this.Vf,this,"Failed to stop DIAL device.")):this.Vf()};
g.k.aa=function(){this.B();this.B=g.Oa;g.Io(this.D);this.C&&this.C.removeUpdateListener(this.X);this.C=null;A7.prototype.aa.call(this)};
g.k.tR=function(a){this.la()||a||(B7(this,"DIAL session died."),this.B(),this.B=g.Oa,this.Vf())};
g.k.Dw=function(a){this.N=k6();if(this.V){var b=new chrome.cast.DialLaunchResponse(!0,UHa(this));a(b);THa(this)}else this.F=(0,g.z)(function(){g.Io(this.D);this.F=g.Oa;this.D=NaN;var c=new chrome.cast.DialLaunchResponse(!0,UHa(this));a(c);THa(this)},this),this.D=g.Fo((0,g.z)(function(){this.F()},this),100)};
g.k.lJ=function(a,b,c){OHa(this.P,this.I.receiver.label,a,this.u.friendlyName,(0,g.z)(function(d){d&&d.token?(this.wt(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Dw(b,c)},this),(0,g.z)(function(d){B7(this,"Failed to get DIAL screen: "+d);
this.Dw(b,c)},this))};g.u(E7,A7);E7.prototype.stop=function(){this.Vf()};
E7.prototype.ly=function(){};
E7.prototype.Um=function(){g.Io(this.B);this.B=NaN;var a=m6(this.P.Pf(),this.u.label);a?this.wt(a):this.Vf(Error("No such screen"))};
E7.prototype.aa=function(){g.Io(this.B);this.B=NaN;A7.prototype.aa.call(this)};g.u(F7,g.P);g.k=F7.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.K);this.P||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.z)(this.DO,this);c=new chrome.cast.ApiConfig(c,(0,g.z)(this.tE,this),f,d,e);c.customDialLaunchCallback=(0,g.z)(this.aN,this);chrome.cast.initialize(c,(0,g.z)(function(){this.la()||
(chrome.cast.addReceiverActionListener(this.D),BHa(),this.B.subscribe("onlineScreenChange",(0,g.z)(this.IG,this)),this.C=WHa(this),chrome.cast.setCustomReceivers(this.C,g.Oa,(0,g.z)(function(h){this.Sc("Failed to set initial custom receivers: "+g.Fj(h))},this)),this.W("yt-remote-cast2-availability-change",H7(this)),b(!0))},this),(0,g.z)(function(h){this.Sc("Failed to initialize API: "+g.Fj(h));
b(!1)},this))};
g.k.tQ=function(a,b){G7("Setting connected screen ID: "+a+" -> "+b);if(this.u){var c=this.u.getScreen();if(!a||c&&c.id!=a)G7("Unsetting old screen status: "+this.u.u.friendlyName),I7(this,null)}if(a&&b){if(!this.u){c=m6(this.B.Pf(),a);if(!c){G7("setConnectedScreenStatus: Unknown screen.");return}var d=VHa(this,c);d||(G7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.C.push(d),chrome.cast.setCustomReceivers(this.C,
g.Oa,(0,g.z)(function(e){this.Sc("Failed to set initial custom receivers: "+g.Fj(e))},this)));
G7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);I7(this,new E7(this.B,d),!0)}this.u.my(b)}else G7("setConnectedScreenStatus: no screen.")};
g.k.uQ=function(a){this.la()?this.Sc("Setting connection data on disposed cast v2"):this.u?this.u.Um(a):this.Sc("Setting connection data without a session")};
g.k.sR=function(){this.la()?this.Sc("Stopping session on disposed cast v2"):this.u?(this.u.stop(),I7(this,null)):G7("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.z)(this.tE,this),(0,g.z)(this.VO,this))};
g.k.aa=function(){this.B.unsubscribe("onlineScreenChange",(0,g.z)(this.IG,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.D);var a=yHa,b=g.Na("yt.mdx.remote.debug.handlers_");g.rb(b||[],a);g.eg(this.u);g.P.prototype.aa.call(this)};
g.k.Sc=function(a){k7("Controller",a)};
g.k.vE=function(a,b){this.u==a&&(b||I7(this,null),this.W("yt-remote-cast2-session-change",b))};
g.k.zO=function(a,b){if(!this.la())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),G7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.u)if(this.u.u.label!=a.label)G7("onReceiverAction_: Stopping active receiver: "+this.u.u.friendlyName),this.u.stop();else{G7("onReceiverAction_: Casting to active receiver.");this.u.getScreen()&&this.W("yt-remote-cast2-session-change",this.u.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:I7(this,
new E7(this.B,a));break;case chrome.cast.ReceiverType.DIAL:I7(this,new D7(this.B,a,this.I));break;case chrome.cast.ReceiverType.CAST:I7(this,new C7(this.B,a));break;default:this.Sc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.u&&this.u.u.label==a.label?this.u.stop():this.Sc("Stopping receiver w/o session: "+a.friendlyName)}else this.Sc("onReceiverAction_ called without receiver.")};
g.k.aN=function(a){if(this.la())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Sc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.u?this.u.u:null;if(!c||c.label!=b.label)return this.Sc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.u.getScreen())return G7("Reselecting dial screen."),
this.W("yt-remote-cast2-session-change",this.u.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Sc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);I7(this,new D7(this.B,b,this.I))}b=this.u;b.I=a;return b.I.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.z)(b.lJ,b,(b.I.extraData||{}).screenId||null)):new Promise((0,g.z)(b.Dw,b))};
g.k.tE=function(a){if(!this.la()){G7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.u)if(b.receiverType==chrome.cast.ReceiverType.CAST)G7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),I7(this,new C7(this.B,b),!0);else{this.Sc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.u.u,d=m6(this.B.Pf(),c.label);d&&h6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(G7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.eg(this.u),this.u=new C7(this.B,b),this.u.subscribe("sessionScreen",(0,g.z)(this.vE,this,this.u)),this.u.Um(null));this.u.ly(a)}}};
g.k.rR=function(){return this.u?this.u.JG():null};
g.k.VO=function(a){this.la()||(this.Sc("Failed to estabilish a session: "+g.Fj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&I7(this,null))};
g.k.DO=function(a){G7("Receiver availability updated: "+a);if(!this.la()){var b=H7(this);this.F=a==chrome.cast.ReceiverAvailability.AVAILABLE;H7(this)!=b&&this.W("yt-remote-cast2-availability-change",H7(this))}};
g.k.IG=function(){this.la()||(this.C=WHa(this),G7("Updating custom receivers: "+g.Fj(this.C)),chrome.cast.setCustomReceivers(this.C,g.Oa,(0,g.z)(function(){this.Sc("Failed to set custom receivers.")},this)),this.W("yt-remote-cast2-availability-change",H7(this)))};
F7.prototype.setLaunchParams=F7.prototype.uQ;F7.prototype.setConnectedScreenStatus=F7.prototype.tQ;F7.prototype.stopSession=F7.prototype.sR;F7.prototype.getCastSession=F7.prototype.rR;F7.prototype.requestSession=F7.prototype.requestSession;F7.prototype.init=F7.prototype.init;F7.prototype.dispose=F7.prototype.dispose;var O7=[];g.k=T7.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";U7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.u=a.trackData,this.Qh=a.hasPrevious,this.hasNext=a.hasNext,this.K=a.playerTime,this.I=a.playerTimeAt,this.F=a.seekableStart,this.B=a.seekableEnd,this.P=a.duration,this.N=a.loadedTime,this.D=a.liveIngestionTime,this.C=!isNaN(this.D))};
g.k.Cb=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.C?this.P+V7(this):this.P};
g.k.clone=function(){return new T7(Z7(this))};g.u(a8,g.P);g.k=a8.prototype;g.k.play=function(){1==this.Ca?(this.u?this.u.play(null,g.Oa,g8(this,"play")):f8(this,"play"),e8(this,1,X7(b8(this))),this.W("remotePlayerChange")):c8(this,this.play)};
g.k.pause=function(){1==this.Ca?(this.u?this.u.pause(null,g.Oa,g8(this,"pause")):f8(this,"pause"),e8(this,2,X7(b8(this))),this.W("remotePlayerChange")):c8(this,this.pause)};
g.k.seekTo=function(a){if(1==this.Ca){if(this.u){var b=b8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Cb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Oa,g8(this,"seekTo",{newTime:a}))}else f8(this,"seekTo",{newTime:a});e8(this,3,a);this.W("remotePlayerChange")}else c8(this,g.Wa(this.seekTo,a))};
g.k.stop=function(){if(1==this.Ca){this.u?this.u.stop(null,g.Oa,g8(this,"stopVideo")):f8(this,"stopVideo");var a=b8(this);a.index=-1;a.videoId="";U7(a);d8(this,a);this.W("remotePlayerChange")}else c8(this,this.stop)};
g.k.setVolume=function(a,b){if(1==this.Ca){var c=b8(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.z)(function(){k7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.Sc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.z)(function(){k7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.Sc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);f8(this,"setVolume",e)}c.muted=b;c.volume=a;d8(this,c)}else c8(this,g.Wa(this.setVolume,a,b))};
g.k.EG=function(a,b){if(1==this.Ca){var c=b8(this),d={videoId:a};b&&(c.u={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Fj(b.style),g.bc(d,c.u));f8(this,"setSubtitlesTrack",d);d8(this,c)}else c8(this,g.Wa(this.EG,a,b))};
g.k.setAudioTrack=function(a,b){if(1==this.Ca){var c=b.getLanguageInfo().getId();f8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=b8(this);d.audioTrackId=c;d8(this,d)}else c8(this,g.Wa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=b8(this);c=c||0;var m={videoId:a,currentIndex:c};Y7(l,a,c);void 0!==b&&(W7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Fj(h));f8(this,"setPlaylist",m);d||d8(this,l)};
g.k.Dt=function(a,b){if(1==this.Ca){if(a&&b){var c=b8(this);Y7(c,a,b);d8(this,c)}f8(this,"previous")}else c8(this,g.Wa(this.Dt,a,b))};
g.k.nextVideo=function(a,b){if(1==this.Ca){if(a&&b){var c=b8(this);Y7(c,a,b);d8(this,c)}f8(this,"next")}else c8(this,g.Wa(this.nextVideo,a,b))};
g.k.NA=function(){1==this.Ca?f8(this,"dismissAutoplay"):c8(this,this.NA)};
g.k.dispose=function(){if(3!=this.Ca){var a=this.Ca;this.Ca=3;this.W("proxyStateChange",a,this.Ca)}g.P.prototype.dispose.call(this)};
g.k.aa=function(){iIa(this);this.C=null;this.D.clear();$7(this,null);g.P.prototype.aa.call(this)};
g.k.fz=function(a){if((a!=this.Ca||2==a)&&3!=this.Ca&&0!=a){var b=this.Ca;this.Ca=a;this.W("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)b=a=this.D,g.ob(b.u)&&(b.u=b.B,b.u.reverse(),b.B=[]),a.u.pop().apply(this);else 3==a&&this.dispose()}};
g.k.vO=function(a,b){this.W(a,b)};
g.k.JM=function(a){if(!a)this.wp(null),$7(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=b8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)k7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,d8(this,b)}};
g.k.wp=function(a){k7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.K);if(this.u=a)this.u.addUpdateListener(this.K),jIa(this),this.W("remotePlayerChange")};
g.k.IM=function(a){a?(jIa(this),this.W("remotePlayerChange")):this.wp(null)};
g.k.Fy=function(){f8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.SM=function(){var a=fIa();a&&$7(this,a)};
g.k.Sc=function(a){k7("CP",a)};g.u(h8,g.P);g.k=h8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.Ab.listId=c);this.Ab.videoId=d;this.Ab.index=h||0;this.Ab.state=3;W7(this.Ab,m);this.D="UNSUPPORTED";i8("Connecting with setPlaylist and params: "+g.Fj(l));this.u.connect({method:"setPlaylist",
params:g.Fj(l)},a,vGa())}else i8("Connecting without params"),this.u.connect({},a,vGa());lIa(this)};
g.k.dispose=function(){this.la()||(this.W("beforeDispose"),j8(this,3));g.P.prototype.dispose.call(this)};
g.k.aa=function(){k8(this);m8(this);l8(this);g.Io(this.K);this.K=NaN;g.Io(this.P);this.P=NaN;this.C=null;g.dp(this.Y);this.Y.length=0;this.u.dispose();g.P.prototype.aa.call(this);this.D=this.I=this.B=this.Ab=this.u=null};
g.k.GI=function(){this.xm(2)};
g.k.OM=function(){i8("Channel opened");this.X&&(this.X=!1,l8(this),this.V=g.Fo((0,g.z)(function(){i8("Timing out waiting for a screen.");this.xm(1)},this),15E3));
zGa(vHa(this.u),this.ba)};
g.k.KM=function(){i8("Channel closed");isNaN(this.F)?r6(!0):r6();this.dispose()};
g.k.LM=function(a){r6();isNaN(this.Co())?(i8("Channel error: "+a+" without reconnection"),this.dispose()):(this.X=!0,i8("Channel error: "+a+" with reconnection in "+this.Co()+" ms"),j8(this,2))};
g.k.MM=function(a){a.params?i8("Received: action="+a.action+", params="+g.Fj(a.params)):i8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=y6(a.params.devices);this.B=g.Pc(a,function(c){return new f6(c)});
a=!!g.jb(this.B,function(c){return"LOUNGE_SCREEN"==c.type});
oIa(this,a);break;case "loungeScreenDisconnected":g.sb(this.B,function(c){return"LOUNGE_SCREEN"==c.type});
oIa(this,!1);break;case "remoteConnected":var b=new f6(y6(a.params.device));g.jb(this.B,function(c){return b?c.id==b.id:!1})||fGa(this.B,b);
break;case "remoteDisconnected":b=new f6(y6(a.params.device));g.sb(this.B,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":qIa(this,a);break;case "nowPlaying":sIa(this,a);break;case "onStateChange":rIa(this,a);break;case "onAdStateChange":tIa(this,a);break;case "onVolumeChanged":uIa(this,a);break;case "onSubtitlesTrackChanged":pIa(this,a);break;case "nowAutoplaying":vIa(this,a);break;case "autoplayDismissed":this.W("autoplayDismissed");break;case "autoplayUpNext":this.I=a.params.videoId||null;this.W("autoplayUpNext",this.I);break;case "onAutoplayModeChanged":this.D=
a.params.autoplayMode;this.W("autoplayModeChange",this.D);"DISABLED"==this.D&&this.W("autoplayDismissed");break;case "onHasPreviousNextChanged":wIa(this,a);break;case "requestAssistedSignIn":this.W("assistedSignInRequested",a.params.authCode);break;default:i8("Unrecognized action: "+a.action)}};
g.k.jQ=function(){if(this.C){var a=this.C;this.C=null;this.Ab.videoId!=a&&n8(this,"getNowPlaying")}};
g.k.wI=function(){var a=3;this.la()||(a=0,isNaN(this.Co())?f7(this.u)&&isNaN(this.F)&&(a=1):a=2);return a};
g.k.xm=function(a){i8("Disconnecting with "+a);k8(this);this.W("beforeDisconnect",a);1==a&&r6();wHa(this.u,a);this.dispose()};
g.k.uI=function(){var a=this.Ab;this.C&&(a=this.Ab.clone(),Y7(a,this.C,a.index));return Z7(a)};
g.k.vQ=function(a){var b=new T7(a);b.videoId&&b.videoId!=this.Ab.videoId&&(this.C=b.videoId,g.Io(this.K),this.K=g.Fo((0,g.z)(this.jQ,this),5E3));var c=[];this.Ab.listId==b.listId&&this.Ab.videoId==b.videoId&&this.Ab.index==b.index||c.push("remoteQueueChange");this.Ab.playerState==b.playerState&&this.Ab.volume==b.volume&&this.Ab.muted==b.muted&&X7(this.Ab)==X7(b)&&g.Fj(this.Ab.u)==g.Fj(b.u)||c.push("remotePlayerChange");this.Ab.reset(a);g.Gb(c,function(d){this.W(d)},this)};
g.k.xB=function(){var a=this.u.I.id,b=g.jb(this.B,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Co=function(){var a=this.u;return a.B.isActive()?a.B.B-g.A():NaN};
g.k.jI=function(){return this.D||"UNSUPPORTED"};
g.k.kI=function(){return this.I||""};
g.k.kR=function(){if(!isNaN(this.Co())){var a=this.u.B;g.tn(a.u);a.start()}};
g.k.rQ=function(a,b){n8(this,a,b);nIa(this)};
g.k.DG=function(){var a=g.wq("SID","")||"",b=g.wq("SAPISID","")||"",c=g.wq("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.qf(g.Ve(a),2);b=g.qf(g.Ve(b),2);c=g.qf(g.Ve(c),2);return g.qf(g.Ve(a+","+b+","+c),2)};
h8.prototype.subscribe=h8.prototype.subscribe;h8.prototype.unsubscribeByKey=h8.prototype.jk;h8.prototype.getProxyState=h8.prototype.wI;h8.prototype.disconnect=h8.prototype.xm;h8.prototype.getPlayerContextData=h8.prototype.uI;h8.prototype.setPlayerContextData=h8.prototype.vQ;h8.prototype.getOtherConnectedRemoteId=h8.prototype.xB;h8.prototype.getReconnectTimeout=h8.prototype.Co;h8.prototype.getAutoplayMode=h8.prototype.jI;h8.prototype.getAutoplayVideoId=h8.prototype.kI;h8.prototype.reconnect=h8.prototype.kR;
h8.prototype.sendMessage=h8.prototype.rQ;h8.prototype.getXsrfToken=h8.prototype.DG;g.u(o8,o7);g.k=o8.prototype;g.k.Pf=function(a){return this.Ie.$_gs(a)};
g.k.contains=function(a){return!!this.Ie.$_c(a)};
g.k.get=function(a){return this.Ie.$_g(a)};
g.k.start=function(){this.Ie.$_st()};
g.k.add=function(a,b,c){this.Ie.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Ie.$_r(a,b,c)};
g.k.ku=function(a,b,c,d){this.Ie.$_un(a,b,c,d)};
g.k.aa=function(){for(var a=0,b=this.u.length;a<b;++a)this.Ie.$_ubk(this.u[a]);this.u.length=0;this.Ie=null;o7.prototype.aa.call(this)};
g.k.oR=function(){this.W("screenChange")};
g.k.bO=function(){this.W("onlineScreenChange")};
x7.prototype.$_st=x7.prototype.start;x7.prototype.$_gspc=x7.prototype.pR;x7.prototype.$_gsppc=x7.prototype.HG;x7.prototype.$_c=x7.prototype.contains;x7.prototype.$_g=x7.prototype.get;x7.prototype.$_a=x7.prototype.add;x7.prototype.$_un=x7.prototype.ku;x7.prototype.$_r=x7.prototype.remove;x7.prototype.$_gs=x7.prototype.Pf;x7.prototype.$_gos=x7.prototype.GG;x7.prototype.$_s=x7.prototype.subscribe;x7.prototype.$_ubk=x7.prototype.jk;var H8=null,G8=!1,p8=null,q8=null,F8=null,u8=[];g.u(I8,g.B);g.k=I8.prototype;g.k.aa=function(){g.B.prototype.aa.call(this);this.u.stop();this.C.stop();this.P.stop();this.X();var a=this.rb;a.unsubscribe("proxyStateChange",this.qE,this);a.unsubscribe("remotePlayerChange",this.Cp,this);a.unsubscribe("remoteQueueChange",this.xt,this);a.unsubscribe("previousNextChange",this.mE,this);a.unsubscribe("nowAutoplaying",this.hE,this);a.unsubscribe("autoplayDismissed",this.ID,this);this.rb=this.B=null};
g.k.VC=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.rb.Ca)if(J8(this)){if(!b8(this.rb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":b8(this.rb).Cb()?this.rb.pause():this.rb.play();break;case "control_play":this.rb.play();break;case "control_pause":this.rb.pause();break;case "control_seek":this.K.GC(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.J.getCurrentTime();L8(this,0===c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.GM=function(a){this.P.CI(a)};
g.k.TQ=function(a){this.VC("control_subtitles_set_track",g.Wb(a)?null:a)};
g.k.OF=function(){var a=this.J.getOption("captions","track");g.Wb(a)||K8(this,a)};
g.k.Dc=function(a){this.B.Dc(a,this.J.getVideoData().lengthSeconds)};
g.k.XD=function(a){if(J8(this)){this.rb.unsubscribe("remotePlayerChange",this.Cp,this);var b=Math.round(a.volume);a=!!a.muted;var c=b8(this.rb);if(b!==c.volume||a!==c.muted)this.rb.setVolume(b,a),this.N.start();this.rb.subscribe("remotePlayerChange",this.Cp,this)}};
g.k.EN=function(){g.Wb(this.D)||IIa(this,this.D);this.F=!1};
g.k.qE=function(a,b){this.C.stop();2===b&&this.LF()};
g.k.Cp=function(){if(J8(this)){this.u.stop();var a=b8(this.rb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.Vd=1;break;case 1082:case 1083:this.B.Vd=0;break;default:this.B.Vd=-1}switch(a.playerState){case 1081:case 1:this.Ad(new g.OK(8));this.KF();break;case 1085:case 3:this.Ad(new g.OK(9));break;case 1083:case 0:this.Ad(new g.OK(2));this.K.stop();this.Dc(this.J.getVideoData().lengthSeconds);break;case 1084:this.Ad(new g.OK(4));break;case 2:this.Ad(new g.OK(4));this.Dc(X7(a));
break;case -1:this.Ad(new g.OK(64));break;case -1E3:this.Ad(new g.OK(128,{errorCode:"mdx.remoteerror",errorMessage:"Este v\u00eddeo no se puede reproducir de forma remota."}))}a=b8(this.rb).u;var b=this.D;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.D=a,IIa(this,a));a=b8(this.rb);-1===a.volume||Math.round(this.J.getVolume())===a.volume&&this.J.isMuted()===a.muted||this.N.isActive()||this.nG()}else HIa(this)};
g.k.mE=function(){this.J.W("mdxpreviousnextchange")};
g.k.xt=function(){J8(this)||HIa(this)};
g.k.hE=function(a){isNaN(a)||this.J.W("mdxnowautoplaying",a)};
g.k.ID=function(){this.J.W("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){J8(this)&&this.rb.setAudioTrack(this.J.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===b8(this.rb).playerState?L8(this,a):b&&this.rb.seekTo(a)};
g.k.nG=function(){if(J8(this)){var a=b8(this.rb);this.events.Bb(this.V);a.muted?this.J.mute():this.J.unMute();this.J.setVolume(a.volume);this.V=this.events.R(this.J,"onVolumeChange",this.XD)}};
g.k.KF=function(){this.u.stop();if(!this.rb.la()){var a=b8(this.rb);a.Cb()&&this.Ad(new g.OK(8));this.Dc(X7(a));this.u.start()}};
g.k.LF=function(){this.C.stop();this.u.stop();var a=this.rb.C.getReconnectTimeout();2==this.rb.Ca&&!isNaN(a)&&this.C.start()};
g.k.Ad=function(a){this.C.stop();var b=this.I;if(!g.TK(b,a)){var c=g.T(a,2);c!==g.T(this.I,2)&&g.t0(this.J.app,c);this.I=a;KIa(this.B,b,a)}};g.u(M8,g.V);M8.prototype.oc=function(){this.u.show()};
M8.prototype.bb=function(){this.u.hide()};
M8.prototype.B=function(){g.jK("https://support.google.com/youtube/answer/7640706")};
M8.prototype.C=function(){e6("mdx-manual-pairing-popup-ok");this.bb()};g.u(N8,g.V);N8.prototype.oc=function(){this.u.show()};
N8.prototype.bb=function(){this.u.hide()};
N8.prototype.B=function(){e6("mdx-privacy-popup-cancel");this.bb()};
N8.prototype.C=function(){e6("mdx-privacy-popup-confirm");this.bb()};g.u(O8,g.V);O8.prototype.B=function(a){JIa(this,a.state)};g.u(P8,g.IZ);P8.prototype.D=function(){var a=this.J.getOption("remote","receivers");a&&1<a.length&&!this.J.getOption("remote","quickCast")?(this.tk=g.Ib(a,this.u,this),g.JZ(this,g.Pc(a,this.u)),a=this.J.getOption("remote","currentReceiver"),this.uc(this.u(a)),this.enable(!0)):this.enable(!1)};
P8.prototype.u=function(a){return a.key};
P8.prototype.eh=function(a){return"cast-selector-receiver"===a?"Reparto...":this.tk[a].name};
P8.prototype.me=function(a){g.IZ.prototype.me.call(this,a);this.J.setOption("remote","currentReceiver",this.tk[a]);this.Sa.bb()};g.u(Q8,g.uS);g.k=Q8.prototype;
g.k.create=function(){var a=this.player.T(),b=g.OB(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.R(a.experiments,"mdx_load_cast_api_bootstrap_script")};BIa(b,a);this.subscriptions.push(g.No("yt-remote-before-disconnect",this.EM,this));this.subscriptions.push(g.No("yt-remote-connection-change",this.EO,this));this.subscriptions.push(g.No("yt-remote-receiver-availability-change",this.oE,this));this.subscriptions.push(g.No("yt-remote-auto-connect",this.CO,this));this.subscriptions.push(g.No("yt-remote-receiver-resumed",
this.BO,this));this.subscriptions.push(g.No("mdx-privacy-popup-confirm",this.ZP,this));this.subscriptions.push(g.No("mdx-privacy-popup-cancel",this.YP,this));this.subscriptions.push(g.No("mdx-manual-pairing-popup-ok",this.AJ,this));this.oE()};
g.k.load=function(){this.player.cancelPlayback();g.uS.prototype.load.call(this);this.Dh=new I8(this,this.player,this.rb);var a=(a=GIa())?a.currentTime:0;var b=E8()?new a8(z8(),void 0):null;0==a&&b&&(a=X7(b8(b)));0!==a&&this.Dc(a);KIa(this,this.xc,this.xc);g.B0(this.player.app,6)};
g.k.unload=function(){this.player.W("mdxautoplaycanceled");this.Kj=this.Zg;g.fg(this.Dh,this.rb);this.rb=this.Dh=null;g.uS.prototype.unload.call(this);g.B0(this.player.app,5);R8(this)};
g.k.aa=function(){g.Oo(this.subscriptions);g.uS.prototype.aa.call(this)};
g.k.di=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.Dh.VC.apply(this.Dh,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.Vd};
g.k.yI=function(){return this.loaded?this.Dh.suggestion:null};
g.k.Qh=function(){return this.rb?b8(this.rb).Qh:!1};
g.k.hasNext=function(){return this.rb?b8(this.rb).hasNext:!1};
g.k.Dc=function(a,b){this.qC=a||0;this.player.W("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.qC};
g.k.getProgressState=function(){var a=b8(this.rb),b=this.player.getVideoData();return{allowSeeking:g.R(this.player.T().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Td():!a.isAdPlaying()&&this.player.Td(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.D+V7(a):a.D,isAtLiveHead:1>=(a.C?a.B+V7(a):a.B)-this.getCurrentTime(),loaded:a.N,seekableEnd:a.C?a.B+V7(a):a.B,seekableStart:0<a.F?a.F+
V7(a):a.F}};
g.k.nextVideo=function(){this.rb&&this.rb.nextVideo()};
g.k.Dt=function(){this.rb&&this.rb.Dt()};
g.k.EM=function(a){1===a&&(this.Nx=this.rb?b8(this.rb):null)};
g.k.EO=function(){var a=E8()?new a8(z8(),void 0):null;if(a){var b=this.Kj;this.loaded&&this.unload();this.rb=a;this.Nx=null;b.key!==this.Zg.key&&(this.Kj=b,this.load())}else g.eg(this.rb),this.rb=null,this.loaded&&(this.unload(),(a=this.Nx)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,X7(a)));this.player.W("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.oE=function(){this.tk=[this.Zg].concat(DIa());var a=A8()||this.Zg;S8(this,a);this.player.va("onMdxReceiversChange")};
g.k.CO=function(){var a=A8();S8(this,a)};
g.k.BO=function(){this.Kj=A8()};
g.k.ZP=function(){this.Fp=!0;R8(this);G8=!1;H8&&C8(H8,1);H8=null};
g.k.YP=function(){this.Fp=!1;R8(this);S8(this,this.Zg);this.Kj=this.Zg;G8=!1;H8=null;this.player.playVideo()};
g.k.AJ=function(){this.Es=!0;R8(this);g.Rs("yt-remote-manual-pairing-warning-shown",!0,2592E3);G8=!1;H8&&C8(H8,1);H8=null};
g.k.Qd=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.tk;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?R7():S8(this,b)),this.loaded?this.Kj:this.Zg;case "quickCast":return 2===this.tk.length&&"cast-selector-receiver"===this.tk[1].key?(b&&R7(),!0):!1}};
g.k.Fy=function(){this.rb.Fy()};
g.k.oh=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.nX.remote=Q8;})(_yt_player);
